/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

/**
 * `error`.
 */
export enum Type {
    Error = "error",
}

/**
 * A short code that describes the reason for the error.
 */
export enum Code {
    BadRequest = "bad_request",
    IncorrectJson = "incorrect_json",
    InvalidCredentials = "invalid_credentials",
}

/**
 * `400`.
 */
export enum Status {
    FourHundred = 400,
}

/**
 * Bad Request (HTTP 400).
 */
export type Error400BadRequestData = {
    /**
     * `error`.
     */
    type?: Type | undefined;
    /**
     * A short code that describes the reason for the error.
     */
    code?: Code | undefined;
    /**
     * `400`.
     */
    status?: Status | undefined;
    /**
     * A human-readable reason for the error.
     */
    message?: string | undefined;
    /**
     * A list of detail objects that further clarify the reason for the error.
     */
    details?: Array<components.ErrorDetail> | undefined;
};

/**
 * Bad Request (HTTP 400).
 */
export class Error400BadRequest extends Error {
    /**
     * `error`.
     */
    type?: Type | undefined;
    /**
     * A short code that describes the reason for the error.
     */
    code?: Code | undefined;
    /**
     * `400`.
     */
    status?: Status | undefined;
    /**
     * A list of detail objects that further clarify the reason for the error.
     */
    details?: Array<components.ErrorDetail> | undefined;

    /** The original data that was passed to this error instance. */
    data$: Error400BadRequestData;

    constructor(err: Error400BadRequestData) {
        super("");
        this.data$ = err;

        if (err.type != null) {
            this.type = err.type;
        }
        if (err.code != null) {
            this.code = err.code;
        }
        if (err.status != null) {
            this.status = err.status;
        }
        if (err.details != null) {
            this.details = err.details;
        }

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "Error400BadRequest";
    }
}

/** @internal */
export namespace Type$ {
    export const inboundSchema = z.nativeEnum(Type);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace Code$ {
    export const inboundSchema = z.nativeEnum(Code);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace Status$ {
    export const inboundSchema = z.nativeEnum(Status);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace Error400BadRequest$ {
    export const inboundSchema: z.ZodType<Error400BadRequest, z.ZodTypeDef, unknown> = z
        .object({
            type: Type$.inboundSchema.optional(),
            code: Code$.inboundSchema.optional(),
            status: Status$.inboundSchema.optional(),
            message: z.string().optional(),
            details: z.array(components.ErrorDetail$.inboundSchema).optional(),
        })
        .transform((v) => {
            return new Error400BadRequest(v);
        });

    export type Outbound = {
        type?: string | undefined;
        code?: string | undefined;
        status?: number | undefined;
        message?: string | undefined;
        details?: Array<components.ErrorDetail$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Error400BadRequest> = z
        .instanceof(Error400BadRequest)
        .transform((v) => v.data$)
        .pipe(
            z.object({
                type: Type$.outboundSchema.optional(),
                code: Code$.outboundSchema.optional(),
                status: Status$.outboundSchema.optional(),
                message: z.string().optional(),
                details: z.array(components.ErrorDetail$.outboundSchema).optional(),
            })
        );
}
