/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

/**
 * `error`.
 */
export enum Error403ForbiddenType {
    Error = "error",
}

/**
 * `forbidden`.
 */
export enum Error403ForbiddenCode {
    Forbidden = "forbidden",
}

/**
 * `403`.
 */
export enum Error403ForbiddenStatus {
    FourHundredAndThree = 403,
}

/**
 * Invalid credentials.
 */
export enum Error403ForbiddenMessage {
    InvalidCredentials = "Invalid credentials",
}

/**
 * Forbidden Error (HTTP 403).
 */
export type Error403ForbiddenData = {
    /**
     * `error`.
     */
    type?: Error403ForbiddenType | undefined;
    /**
     * `forbidden`.
     */
    code?: Error403ForbiddenCode | undefined;
    /**
     * `403`.
     */
    status?: Error403ForbiddenStatus | undefined;
    /**
     * Invalid credentials.
     */
    message?: Error403ForbiddenMessage | undefined;
    /**
     * A list of detail objects that further clarify the reason for the error.
     *
     * @remarks
     * Not every error supports more detail.
     */
    details?: Array<components.ErrorDetail> | undefined;
};

/**
 * Forbidden Error (HTTP 403).
 */
export class Error403Forbidden extends Error {
    /**
     * `error`.
     */
    type?: Error403ForbiddenType | undefined;
    /**
     * `forbidden`.
     */
    code?: Error403ForbiddenCode | undefined;
    /**
     * `403`.
     */
    status?: Error403ForbiddenStatus | undefined;
    /**
     * A list of detail objects that further clarify the reason for the error.
     *
     * @remarks
     * Not every error supports more detail.
     */
    details?: Array<components.ErrorDetail> | undefined;

    /** The original data that was passed to this error instance. */
    data$: Error403ForbiddenData;

    constructor(err: Error403ForbiddenData) {
        super("");
        this.data$ = err;

        if (err.type != null) {
            this.type = err.type;
        }
        if (err.code != null) {
            this.code = err.code;
        }
        if (err.status != null) {
            this.status = err.status;
        }
        if (err.details != null) {
            this.details = err.details;
        }

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "Error403Forbidden";
    }
}

/** @internal */
export const Error403ForbiddenType$: z.ZodNativeEnum<typeof Error403ForbiddenType> =
    z.nativeEnum(Error403ForbiddenType);

/** @internal */
export const Error403ForbiddenCode$: z.ZodNativeEnum<typeof Error403ForbiddenCode> =
    z.nativeEnum(Error403ForbiddenCode);

/** @internal */
export const Error403ForbiddenStatus$: z.ZodNativeEnum<typeof Error403ForbiddenStatus> =
    z.nativeEnum(Error403ForbiddenStatus);

/** @internal */
export const Error403ForbiddenMessage$: z.ZodNativeEnum<typeof Error403ForbiddenMessage> =
    z.nativeEnum(Error403ForbiddenMessage);

/** @internal */
export namespace Error403Forbidden$ {
    export type Inbound = {
        type?: Error403ForbiddenType | undefined;
        code?: Error403ForbiddenCode | undefined;
        status?: Error403ForbiddenStatus | undefined;
        message?: Error403ForbiddenMessage | undefined;
        details?: Array<components.ErrorDetail$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<Error403Forbidden, z.ZodTypeDef, Inbound> = z
        .object({
            type: Error403ForbiddenType$.optional(),
            code: Error403ForbiddenCode$.optional(),
            status: Error403ForbiddenStatus$.optional(),
            message: Error403ForbiddenMessage$.optional(),
            details: z.array(components.ErrorDetail$.inboundSchema).optional(),
        })
        .transform((v) => {
            return new Error403Forbidden({
                ...(v.type === undefined ? null : { type: v.type }),
                ...(v.code === undefined ? null : { code: v.code }),
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.message === undefined ? null : { message: v.message }),
                ...(v.details === undefined ? null : { details: v.details }),
            });
        });

    export type Outbound = {
        type?: Error403ForbiddenType | undefined;
        code?: Error403ForbiddenCode | undefined;
        status?: Error403ForbiddenStatus | undefined;
        message?: Error403ForbiddenMessage | undefined;
        details?: Array<components.ErrorDetail$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Error403Forbidden> = z
        .instanceof(Error403Forbidden)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    type: Error403ForbiddenType$.optional(),
                    code: Error403ForbiddenCode$.optional(),
                    status: Error403ForbiddenStatus$.optional(),
                    message: Error403ForbiddenMessage$.optional(),
                    details: z.array(components.ErrorDetail$.outboundSchema).optional(),
                })
                .transform((v) => {
                    return {
                        ...(v.type === undefined ? null : { type: v.type }),
                        ...(v.code === undefined ? null : { code: v.code }),
                        ...(v.status === undefined ? null : { status: v.status }),
                        ...(v.message === undefined ? null : { message: v.message }),
                        ...(v.details === undefined ? null : { details: v.details }),
                    };
                })
        );
}
