/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as components from "../components/index.js";
import { Gr4vyError } from "./gr4vyerror.js";

export type Error500Data = {
  /**
   * Always `error`.
   */
  type?: "error" | undefined;
  /**
   * Always `server_error`
   */
  code?: string | undefined;
  /**
   * Always `500`.
   */
  status?: number | undefined;
  /**
   * A human readable message that provides more context to the error.
   */
  message?: string | undefined;
  /**
   * A list of details that further ellaborate on the error.
   */
  details?: Array<components.ErrorDetail> | undefined;
};

export class Error500 extends Gr4vyError {
  /**
   * Always `error`.
   */
  type?: "error" | undefined;
  /**
   * Always `server_error`
   */
  code?: string | undefined;
  /**
   * Always `500`.
   */
  status?: number | undefined;
  /**
   * A list of details that further ellaborate on the error.
   */
  details?: Array<components.ErrorDetail> | undefined;

  /** The original data that was passed to this error instance. */
  data$: Error500Data;

  constructor(
    err: Error500Data,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.type != null) this.type = err.type;
    if (err.code != null) this.code = err.code;
    if (err.status != null) this.status = err.status;
    if (err.details != null) this.details = err.details;

    this.name = "Error500";
  }
}

/** @internal */
export const Error500$inboundSchema: z.ZodType<
  Error500,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("error").default("error"),
  code: z.string().default("server_error"),
  status: z.number().int().default(500),
  message: z.string().default("Request could not be processed"),
  details: z.array(components.ErrorDetail$inboundSchema).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new Error500(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
