/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { giftCardsActivationsCreate } from "../funcs/giftCardsActivationsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Activations extends ClientSDK {
  /**
   * Activate a gift card
   *
   * @remarks
   * Activate a physical gift card through the primary gift card service.
   */
  async create(
    giftCardActivationCreate: components.GiftCardActivationCreate,
    idempotencyKey?: string | null | undefined,
    merchantAccountId?: string | null | undefined,
    options?: RequestOptions,
  ): Promise<components.GiftCard> {
    return unwrapAsync(giftCardsActivationsCreate(
      this,
      giftCardActivationCreate,
      idempotencyKey,
      merchantAccountId,
      options,
    ));
  }
}
