/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import * as schemas$ from "../lib/schemas";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as errors from "../models/errors";
import * as operations from "../models/operations";
import * as z from "zod";

export class VaultForward extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    /**
     * Forward PCI data
     *
     * @remarks
     * Forward an API call to a PCI endpoint. The request body is evaluated and any template fields are replaced by the card data before the request is sent to the given destination.
     */
    async makeVaultForward(
        request: operations.MakeVaultForwardRequest,
        options?: RequestOptions
    ): Promise<string> {
        const input$ = request;
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "*/*");
        headers$.set("Accept", "*/*");

        const payload$ = schemas$.parse(
            input$,
            (value$) => operations.MakeVaultForwardRequest$.outboundSchema.parse(value$),
            "Input validation failed"
        );
        const body$ = payload$.RequestBody;

        const path$ = this.templateURLComponent("/vault-forward")();

        const query$ = "";

        headers$.set(
            "x-vault-forward-header-{HEADER_NAME}",
            enc$.encodeSimple(
                "x-vault-forward-header-{HEADER_NAME}",
                payload$["x-vault-forward-header-{HEADER_NAME}"],
                { explode: false, charEncoding: "none" }
            )
        );
        headers$.set(
            "x-vault-forward-http-method",
            enc$.encodeSimple(
                "x-vault-forward-http-method",
                payload$["x-vault-forward-http-method"],
                { explode: false, charEncoding: "none" }
            )
        );
        headers$.set(
            "x-vault-forward-payment-methods",
            enc$.encodeSimple(
                "x-vault-forward-payment-methods",
                payload$["x-vault-forward-payment-methods"],
                { explode: false, charEncoding: "none" }
            )
        );
        headers$.set(
            "x-vault-forward-timeout",
            enc$.encodeSimple("x-vault-forward-timeout", payload$["x-vault-forward-timeout"], {
                explode: false,
                charEncoding: "none",
            })
        );
        headers$.set(
            "x-vault-forward-url",
            enc$.encodeSimple("x-vault-forward-url", payload$["x-vault-forward-url"], {
                explode: false,
                charEncoding: "none",
            })
        );

        let security$;
        if (typeof this.options$.bearerAuth === "function") {
            security$ = { bearerAuth: await this.options$.bearerAuth() };
        } else if (this.options$.bearerAuth) {
            security$ = { bearerAuth: this.options$.bearerAuth };
        } else {
            security$ = {};
        }
        const context = {
            operationID: "make-vault-forward",
            oAuth2Scopes: [],
            securitySource: this.options$.bearerAuth,
        };
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const doOptions = { context, errorCodes: ["400", "401", "4XX", "5XX"] };
        const request$ = this.createRequest$(
            context,
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                query: query$,
                body: body$,
            },
            options
        );

        const response = await this.do$(request$, doOptions);

        const responseFields$ = {
            HttpMeta: { Response: response, Request: request$ },
        };

        const [result$] = await this.matcher<string>()
            .text(200, z.string(), { ctype: "*/*" })
            .json(400, errors.Error400BadRequest$, { err: true })
            .json(401, errors.Error401Unauthorized$, { err: true })
            .fail(["4XX", "5XX"])
            .match(response, { extraFields: responseFields$ });

        return result$;
    }
}
