/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type CaptureTransactionRequest = {
    /**
     * The ID for the transaction to get the information for.
     */
    transactionId: string;
    transactionCaptureRequest?: components.TransactionCaptureRequest | undefined;
};

/** @internal */
export namespace CaptureTransactionRequest$ {
    export const inboundSchema: z.ZodType<CaptureTransactionRequest, z.ZodTypeDef, unknown> = z
        .object({
            transaction_id: z.string(),
            TransactionCaptureRequest:
                components.TransactionCaptureRequest$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                transaction_id: "transactionId",
                TransactionCaptureRequest: "transactionCaptureRequest",
            });
        });

    export type Outbound = {
        transaction_id: string;
        TransactionCaptureRequest?: components.TransactionCaptureRequest$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CaptureTransactionRequest> = z
        .object({
            transactionId: z.string(),
            transactionCaptureRequest:
                components.TransactionCaptureRequest$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                transactionId: "transaction_id",
                transactionCaptureRequest: "TransactionCaptureRequest",
            });
        });
}
