/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreatePazeMobileSessionGlobals = {
  merchantAccountId?: string | undefined;
};

export type CreatePazeMobileSessionRequest = {
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  pazeMobileSessionCreateRequest: components.PazeMobileSessionCreateRequest;
};

/** @internal */
export type CreatePazeMobileSessionRequest$Outbound = {
  merchantAccountId?: string | null | undefined;
  PazeMobileSessionCreateRequest:
    components.PazeMobileSessionCreateRequest$Outbound;
};

/** @internal */
export const CreatePazeMobileSessionRequest$outboundSchema: z.ZodType<
  CreatePazeMobileSessionRequest$Outbound,
  z.ZodTypeDef,
  CreatePazeMobileSessionRequest
> = z.object({
  merchantAccountId: z.nullable(z.string()).optional(),
  pazeMobileSessionCreateRequest:
    components.PazeMobileSessionCreateRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    pazeMobileSessionCreateRequest: "PazeMobileSessionCreateRequest",
  });
});

export function createPazeMobileSessionRequestToJSON(
  createPazeMobileSessionRequest: CreatePazeMobileSessionRequest,
): string {
  return JSON.stringify(
    CreatePazeMobileSessionRequest$outboundSchema.parse(
      createPazeMobileSessionRequest,
    ),
  );
}
