/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateFullTransactionRefundGlobals = {
  merchantAccountId?: string | undefined;
};

export type CreateFullTransactionRefundRequest = {
  /**
   * The ID of the transaction
   */
  transactionId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  transactionRefundAllCreate?:
    | components.TransactionRefundAllCreate
    | null
    | undefined;
};

/** @internal */
export type CreateFullTransactionRefundRequest$Outbound = {
  transaction_id: string;
  merchantAccountId?: string | null | undefined;
  TransactionRefundAllCreate?:
    | components.TransactionRefundAllCreate$Outbound
    | null
    | undefined;
};

/** @internal */
export const CreateFullTransactionRefundRequest$outboundSchema: z.ZodType<
  CreateFullTransactionRefundRequest$Outbound,
  z.ZodTypeDef,
  CreateFullTransactionRefundRequest
> = z.object({
  transactionId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
  transactionRefundAllCreate: z.nullable(
    components.TransactionRefundAllCreate$outboundSchema,
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    transactionId: "transaction_id",
    transactionRefundAllCreate: "TransactionRefundAllCreate",
  });
});

export function createFullTransactionRefundRequestToJSON(
  createFullTransactionRefundRequest: CreateFullTransactionRefundRequest,
): string {
  return JSON.stringify(
    CreateFullTransactionRefundRequest$outboundSchema.parse(
      createFullTransactionRefundRequest,
    ),
  );
}
