/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateGooglePayDigitalWalletSessionGlobals = {
  merchantAccountId?: string | undefined;
};

export type CreateGooglePayDigitalWalletSessionRequest = {
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  googlePaySessionRequest: components.GooglePaySessionRequest;
};

/** @internal */
export type CreateGooglePayDigitalWalletSessionRequest$Outbound = {
  merchantAccountId?: string | null | undefined;
  GooglePaySessionRequest: components.GooglePaySessionRequest$Outbound;
};

/** @internal */
export const CreateGooglePayDigitalWalletSessionRequest$outboundSchema:
  z.ZodType<
    CreateGooglePayDigitalWalletSessionRequest$Outbound,
    z.ZodTypeDef,
    CreateGooglePayDigitalWalletSessionRequest
  > = z.object({
    merchantAccountId: z.nullable(z.string()).optional(),
    googlePaySessionRequest: components.GooglePaySessionRequest$outboundSchema,
  }).transform((v) => {
    return remap$(v, {
      googlePaySessionRequest: "GooglePaySessionRequest",
    });
  });

export function createGooglePayDigitalWalletSessionRequestToJSON(
  createGooglePayDigitalWalletSessionRequest:
    CreateGooglePayDigitalWalletSessionRequest,
): string {
  return JSON.stringify(
    CreateGooglePayDigitalWalletSessionRequest$outboundSchema.parse(
      createGooglePayDigitalWalletSessionRequest,
    ),
  );
}
