/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type DeleteVaultForwardConfigRequest = {
    /**
     * The ID of the Vault Forward configuration.
     */
    configId: string;
};

/** @internal */
export const DeleteVaultForwardConfigRequest$inboundSchema: z.ZodType<
    DeleteVaultForwardConfigRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        config_id: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            config_id: "configId",
        });
    });

/** @internal */
export type DeleteVaultForwardConfigRequest$Outbound = {
    config_id: string;
};

/** @internal */
export const DeleteVaultForwardConfigRequest$outboundSchema: z.ZodType<
    DeleteVaultForwardConfigRequest$Outbound,
    z.ZodTypeDef,
    DeleteVaultForwardConfigRequest
> = z
    .object({
        configId: z.string(),
    })
    .transform((v) => {
        return remap$(v, {
            configId: "config_id",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteVaultForwardConfigRequest$ {
    /** @deprecated use `DeleteVaultForwardConfigRequest$inboundSchema` instead. */
    export const inboundSchema = DeleteVaultForwardConfigRequest$inboundSchema;
    /** @deprecated use `DeleteVaultForwardConfigRequest$outboundSchema` instead. */
    export const outboundSchema = DeleteVaultForwardConfigRequest$outboundSchema;
    /** @deprecated use `DeleteVaultForwardConfigRequest$Outbound` instead. */
    export type Outbound = DeleteVaultForwardConfigRequest$Outbound;
}
