/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteThreeDsConfigurationRequest = {
  /**
   * The ID of the merchant account.
   */
  merchantAccountId: string;
  /**
   * The ID of the 3DS configuration for a merchant account.
   */
  threeDsConfigurationId: string;
};

/** @internal */
export type DeleteThreeDsConfigurationRequest$Outbound = {
  merchant_account_id: string;
  three_ds_configuration_id: string;
};

/** @internal */
export const DeleteThreeDsConfigurationRequest$outboundSchema: z.ZodType<
  DeleteThreeDsConfigurationRequest$Outbound,
  z.ZodTypeDef,
  DeleteThreeDsConfigurationRequest
> = z.object({
  merchantAccountId: z.string(),
  threeDsConfigurationId: z.string(),
}).transform((v) => {
  return remap$(v, {
    merchantAccountId: "merchant_account_id",
    threeDsConfigurationId: "three_ds_configuration_id",
  });
});

export function deleteThreeDsConfigurationRequestToJSON(
  deleteThreeDsConfigurationRequest: DeleteThreeDsConfigurationRequest,
): string {
  return JSON.stringify(
    DeleteThreeDsConfigurationRequest$outboundSchema.parse(
      deleteThreeDsConfigurationRequest,
    ),
  );
}
