/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetBuyerShippingDetailsGlobals = {
  merchantAccountId?: string | undefined;
};

export type GetBuyerShippingDetailsRequest = {
  /**
   * The ID of the buyer to retrieve shipping details for.
   */
  buyerId: string;
  /**
   * The ID of the shipping details to retrieve.
   */
  shippingDetailsId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type GetBuyerShippingDetailsRequest$Outbound = {
  buyer_id: string;
  shipping_details_id: string;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const GetBuyerShippingDetailsRequest$outboundSchema: z.ZodType<
  GetBuyerShippingDetailsRequest$Outbound,
  z.ZodTypeDef,
  GetBuyerShippingDetailsRequest
> = z.object({
  buyerId: z.string(),
  shippingDetailsId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    buyerId: "buyer_id",
    shippingDetailsId: "shipping_details_id",
  });
});

export function getBuyerShippingDetailsRequestToJSON(
  getBuyerShippingDetailsRequest: GetBuyerShippingDetailsRequest,
): string {
  return JSON.stringify(
    GetBuyerShippingDetailsRequest$outboundSchema.parse(
      getBuyerShippingDetailsRequest,
    ),
  );
}
