/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetBuyerGlobals = {
  merchantAccountId?: string | undefined;
};

export type GetBuyerRequest = {
  /**
   * The ID of the buyer to retrieve.
   */
  buyerId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type GetBuyerRequest$Outbound = {
  buyer_id: string;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const GetBuyerRequest$outboundSchema: z.ZodType<
  GetBuyerRequest$Outbound,
  z.ZodTypeDef,
  GetBuyerRequest
> = z.object({
  buyerId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    buyerId: "buyer_id",
  });
});

export function getBuyerRequestToJSON(
  getBuyerRequest: GetBuyerRequest,
): string {
  return JSON.stringify(GetBuyerRequest$outboundSchema.parse(getBuyerRequest));
}
