/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetCheckoutSessionGlobals = {
  merchantAccountId?: string | undefined;
};

export type GetCheckoutSessionRequest = {
  /**
   * The ID of the checkout session.
   */
  sessionId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type GetCheckoutSessionRequest$Outbound = {
  session_id: string;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const GetCheckoutSessionRequest$outboundSchema: z.ZodType<
  GetCheckoutSessionRequest$Outbound,
  z.ZodTypeDef,
  GetCheckoutSessionRequest
> = z.object({
  sessionId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    sessionId: "session_id",
  });
});

export function getCheckoutSessionRequestToJSON(
  getCheckoutSessionRequest: GetCheckoutSessionRequest,
): string {
  return JSON.stringify(
    GetCheckoutSessionRequest$outboundSchema.parse(getCheckoutSessionRequest),
  );
}
