/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetTransactionCaptureGlobals = {
  merchantAccountId?: string | undefined;
};

export type GetTransactionCaptureRequest = {
  /**
   * The unique identifier of the transaction.
   */
  transactionId: string;
  /**
   * The unique identifier of the capture.
   */
  captureId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type GetTransactionCaptureRequest$Outbound = {
  transaction_id: string;
  capture_id: string;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const GetTransactionCaptureRequest$outboundSchema: z.ZodType<
  GetTransactionCaptureRequest$Outbound,
  z.ZodTypeDef,
  GetTransactionCaptureRequest
> = z.object({
  transactionId: z.string(),
  captureId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    transactionId: "transaction_id",
    captureId: "capture_id",
  });
});

export function getTransactionCaptureRequestToJSON(
  getTransactionCaptureRequest: GetTransactionCaptureRequest,
): string {
  return JSON.stringify(
    GetTransactionCaptureRequest$outboundSchema.parse(
      getTransactionCaptureRequest,
    ),
  );
}
