/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type InboundWebhookRequest = {
    /**
     * Opaque data representing the service information associated with
     *
     * @remarks
     * the webhook endpoint.
     */
    payload: string;
    /**
     * Signature of the opaque data with the service information
     *
     * @remarks
     * used for the webhook endpoint.
     */
    signature: string;
};

/** @internal */
export namespace InboundWebhookRequest$ {
    export const inboundSchema: z.ZodType<InboundWebhookRequest, z.ZodTypeDef, unknown> = z.object({
        payload: z.string(),
        signature: z.string(),
    });

    export type Outbound = {
        payload: string;
        signature: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InboundWebhookRequest> =
        z.object({
            payload: z.string(),
            signature: z.string(),
        });
}
