/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type IncrementTransactionAuthorizationGlobals = {
  merchantAccountId?: string | undefined;
};

export type IncrementTransactionAuthorizationRequest = {
  /**
   * The unique identifier of the transaction.
   */
  transactionId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  /**
   * A unique key that identifies this request. Providing this header will make this an idempotent request. We recommend using V4 UUIDs, or another random string with enough entropy to avoid collisions.
   */
  idempotencyKey?: string | null | undefined;
  transactionAuthorizationIncrementCreate:
    components.TransactionAuthorizationIncrementCreate;
};

/** @internal */
export type IncrementTransactionAuthorizationRequest$Outbound = {
  transaction_id: string;
  merchantAccountId?: string | null | undefined;
  "idempotency-key"?: string | null | undefined;
  TransactionAuthorizationIncrementCreate:
    components.TransactionAuthorizationIncrementCreate$Outbound;
};

/** @internal */
export const IncrementTransactionAuthorizationRequest$outboundSchema: z.ZodType<
  IncrementTransactionAuthorizationRequest$Outbound,
  z.ZodTypeDef,
  IncrementTransactionAuthorizationRequest
> = z.object({
  transactionId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
  idempotencyKey: z.nullable(z.string()).optional(),
  transactionAuthorizationIncrementCreate:
    components.TransactionAuthorizationIncrementCreate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    transactionId: "transaction_id",
    idempotencyKey: "idempotency-key",
    transactionAuthorizationIncrementCreate:
      "TransactionAuthorizationIncrementCreate",
  });
});

export function incrementTransactionAuthorizationRequestToJSON(
  incrementTransactionAuthorizationRequest:
    IncrementTransactionAuthorizationRequest,
): string {
  return JSON.stringify(
    IncrementTransactionAuthorizationRequest$outboundSchema.parse(
      incrementTransactionAuthorizationRequest,
    ),
  );
}
