/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListPaymentMethodPaymentServiceTokensGlobals = {
  merchantAccountId?: string | undefined;
};

export type ListPaymentMethodPaymentServiceTokensRequest = {
  /**
   * The ID of the payment method
   */
  paymentMethodId: string;
  /**
   * The ID of the payment service
   */
  paymentServiceId?: string | null | undefined;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type ListPaymentMethodPaymentServiceTokensRequest$Outbound = {
  payment_method_id: string;
  payment_service_id?: string | null | undefined;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const ListPaymentMethodPaymentServiceTokensRequest$outboundSchema:
  z.ZodType<
    ListPaymentMethodPaymentServiceTokensRequest$Outbound,
    z.ZodTypeDef,
    ListPaymentMethodPaymentServiceTokensRequest
  > = z.object({
    paymentMethodId: z.string(),
    paymentServiceId: z.nullable(z.string()).optional(),
    merchantAccountId: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      paymentMethodId: "payment_method_id",
      paymentServiceId: "payment_service_id",
    });
  });

export function listPaymentMethodPaymentServiceTokensRequestToJSON(
  listPaymentMethodPaymentServiceTokensRequest:
    ListPaymentMethodPaymentServiceTokensRequest,
): string {
  return JSON.stringify(
    ListPaymentMethodPaymentServiceTokensRequest$outboundSchema.parse(
      listPaymentMethodPaymentServiceTokensRequest,
    ),
  );
}
