/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListBuyersGlobals = {
  merchantAccountId?: string | undefined;
};

export type ListBuyersRequest = {
  /**
   * A pointer to the page of results to return.
   */
  cursor?: string | null | undefined;
  /**
   * The maximum number of items that are at returned.
   */
  limit?: number | undefined;
  /**
   * Filters the results to only the buyers for which the `display_name` or `external_identifier` matches this value.
   */
  search?: string | null | undefined;
  /**
   * Filters the results to only the buyers for which the `external_identifier` matches this value.
   */
  externalIdentifier?: string | null | undefined;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

export type ListBuyersResponse = {
  result: components.Buyers;
};

/** @internal */
export type ListBuyersRequest$Outbound = {
  cursor?: string | null | undefined;
  limit: number;
  search?: string | null | undefined;
  external_identifier?: string | null | undefined;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const ListBuyersRequest$outboundSchema: z.ZodType<
  ListBuyersRequest$Outbound,
  z.ZodTypeDef,
  ListBuyersRequest
> = z.object({
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  search: z.nullable(z.string()).optional(),
  externalIdentifier: z.nullable(z.string()).optional(),
  merchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    externalIdentifier: "external_identifier",
  });
});

export function listBuyersRequestToJSON(
  listBuyersRequest: ListBuyersRequest,
): string {
  return JSON.stringify(
    ListBuyersRequest$outboundSchema.parse(listBuyersRequest),
  );
}

/** @internal */
export const ListBuyersResponse$inboundSchema: z.ZodType<
  ListBuyersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.Buyers$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listBuyersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListBuyersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBuyersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBuyersResponse' from JSON`,
  );
}
