/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ListCardSchemeDefinitionsGlobals = {
  merchantAccountId?: string | undefined;
};

export type ListCardSchemeDefinitionsRequest = {
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type ListCardSchemeDefinitionsRequest$Outbound = {
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const ListCardSchemeDefinitionsRequest$outboundSchema: z.ZodType<
  ListCardSchemeDefinitionsRequest$Outbound,
  z.ZodTypeDef,
  ListCardSchemeDefinitionsRequest
> = z.object({
  merchantAccountId: z.nullable(z.string()).optional(),
});

export function listCardSchemeDefinitionsRequestToJSON(
  listCardSchemeDefinitionsRequest: ListCardSchemeDefinitionsRequest,
): string {
  return JSON.stringify(
    ListCardSchemeDefinitionsRequest$outboundSchema.parse(
      listCardSchemeDefinitionsRequest,
    ),
  );
}
