/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ListBuyerShippingDetailsRequest = {
    /**
     * The unique ID for a buyer.
     */
    buyerId: string;
};

/** @internal */
export namespace ListBuyerShippingDetailsRequest$ {
    export type Inbound = {
        buyer_id: string;
    };

    export const inboundSchema: z.ZodType<ListBuyerShippingDetailsRequest, z.ZodTypeDef, Inbound> =
        z
            .object({
                buyer_id: z.string(),
            })
            .transform((v) => {
                return {
                    buyerId: v.buyer_id,
                };
            });

    export type Outbound = {
        buyer_id: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ListBuyerShippingDetailsRequest
    > = z
        .object({
            buyerId: z.string(),
        })
        .transform((v) => {
            return {
                buyer_id: v.buyerId,
            };
        });
}
