/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListTransactionRefundsGlobals = {
  merchantAccountId?: string | undefined;
};

export type ListTransactionRefundsRequest = {
  /**
   * The ID of the transaction
   */
  transactionId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type ListTransactionRefundsRequest$Outbound = {
  transaction_id: string;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const ListTransactionRefundsRequest$outboundSchema: z.ZodType<
  ListTransactionRefundsRequest$Outbound,
  z.ZodTypeDef,
  ListTransactionRefundsRequest
> = z.object({
  transactionId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    transactionId: "transaction_id",
  });
});

export function listTransactionRefundsRequestToJSON(
  listTransactionRefundsRequest: ListTransactionRefundsRequest,
): string {
  return JSON.stringify(
    ListTransactionRefundsRequest$outboundSchema.parse(
      listTransactionRefundsRequest,
    ),
  );
}
