/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListMerchantAccountsRequest = {
  /**
   * A pointer to the page of results to return.
   */
  cursor?: string | null | undefined;
  /**
   * The maximum number of items that are at returned.
   */
  limit?: number | undefined;
  /**
   * The search term to filter merchant accounts by.
   */
  search?: string | null | undefined;
};

export type ListMerchantAccountsResponse = {
  result: components.MerchantAccounts;
};

/** @internal */
export type ListMerchantAccountsRequest$Outbound = {
  cursor?: string | null | undefined;
  limit: number;
  search?: string | null | undefined;
};

/** @internal */
export const ListMerchantAccountsRequest$outboundSchema: z.ZodType<
  ListMerchantAccountsRequest$Outbound,
  z.ZodTypeDef,
  ListMerchantAccountsRequest
> = z.object({
  cursor: z.nullable(z.string()).optional(),
  limit: z.number().int().default(20),
  search: z.nullable(z.string()).optional(),
});

export function listMerchantAccountsRequestToJSON(
  listMerchantAccountsRequest: ListMerchantAccountsRequest,
): string {
  return JSON.stringify(
    ListMerchantAccountsRequest$outboundSchema.parse(
      listMerchantAccountsRequest,
    ),
  );
}

/** @internal */
export const ListMerchantAccountsResponse$inboundSchema: z.ZodType<
  ListMerchantAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.MerchantAccounts$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function listMerchantAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMerchantAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMerchantAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMerchantAccountsResponse' from JSON`,
  );
}
