/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ResumePaymentMethodNetworkTokenGlobals = {
  merchantAccountId?: string | undefined;
};

export type ResumePaymentMethodNetworkTokenRequest = {
  /**
   * The ID of the payment method
   */
  paymentMethodId: string;
  /**
   * The ID of the network token
   */
  networkTokenId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export type ResumePaymentMethodNetworkTokenRequest$Outbound = {
  payment_method_id: string;
  network_token_id: string;
  merchantAccountId?: string | null | undefined;
};

/** @internal */
export const ResumePaymentMethodNetworkTokenRequest$outboundSchema: z.ZodType<
  ResumePaymentMethodNetworkTokenRequest$Outbound,
  z.ZodTypeDef,
  ResumePaymentMethodNetworkTokenRequest
> = z.object({
  paymentMethodId: z.string(),
  networkTokenId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    paymentMethodId: "payment_method_id",
    networkTokenId: "network_token_id",
  });
});

export function resumePaymentMethodNetworkTokenRequestToJSON(
  resumePaymentMethodNetworkTokenRequest:
    ResumePaymentMethodNetworkTokenRequest,
): string {
  return JSON.stringify(
    ResumePaymentMethodNetworkTokenRequest$outboundSchema.parse(
      resumePaymentMethodNetworkTokenRequest,
    ),
  );
}
