/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type ReviewPazeMobileSessionGlobals = {
  merchantAccountId?: string | undefined;
};

export type ReviewPazeMobileSessionRequest = {
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  pazeSessionReviewRequest: components.PazeSessionReviewRequest;
};

/** @internal */
export type ReviewPazeMobileSessionRequest$Outbound = {
  merchantAccountId?: string | null | undefined;
  PazeSessionReviewRequest: components.PazeSessionReviewRequest$Outbound;
};

/** @internal */
export const ReviewPazeMobileSessionRequest$outboundSchema: z.ZodType<
  ReviewPazeMobileSessionRequest$Outbound,
  z.ZodTypeDef,
  ReviewPazeMobileSessionRequest
> = z.object({
  merchantAccountId: z.nullable(z.string()).optional(),
  pazeSessionReviewRequest: components.PazeSessionReviewRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    pazeSessionReviewRequest: "PazeSessionReviewRequest",
  });
});

export function reviewPazeMobileSessionRequestToJSON(
  reviewPazeMobileSessionRequest: ReviewPazeMobileSessionRequest,
): string {
  return JSON.stringify(
    ReviewPazeMobileSessionRequest$outboundSchema.parse(
      reviewPazeMobileSessionRequest,
    ),
  );
}
