/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UnregisterDigitalWalletDomainGlobals = {
  merchantAccountId?: string | undefined;
};

export type UnregisterDigitalWalletDomainRequest = {
  digitalWalletId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  digitalWalletDomain: components.DigitalWalletDomain;
};

/** @internal */
export type UnregisterDigitalWalletDomainRequest$Outbound = {
  digital_wallet_id: string;
  merchantAccountId?: string | null | undefined;
  DigitalWalletDomain: components.DigitalWalletDomain$Outbound;
};

/** @internal */
export const UnregisterDigitalWalletDomainRequest$outboundSchema: z.ZodType<
  UnregisterDigitalWalletDomainRequest$Outbound,
  z.ZodTypeDef,
  UnregisterDigitalWalletDomainRequest
> = z.object({
  digitalWalletId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
  digitalWalletDomain: components.DigitalWalletDomain$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    digitalWalletId: "digital_wallet_id",
    digitalWalletDomain: "DigitalWalletDomain",
  });
});

export function unregisterDigitalWalletDomainRequestToJSON(
  unregisterDigitalWalletDomainRequest: UnregisterDigitalWalletDomainRequest,
): string {
  return JSON.stringify(
    UnregisterDigitalWalletDomainRequest$outboundSchema.parse(
      unregisterDigitalWalletDomainRequest,
    ),
  );
}
