/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type UpdateCheckoutSessionRequest = {
    /**
     * The unique ID for a Checkout Session.
     */
    checkoutSessionId: string;
    checkoutSessionUpdateRequest?: components.CheckoutSessionUpdateRequest | undefined;
};

/** @internal */
export namespace UpdateCheckoutSessionRequest$ {
    export const inboundSchema: z.ZodType<UpdateCheckoutSessionRequest, z.ZodTypeDef, unknown> = z
        .object({
            checkout_session_id: z.string(),
            CheckoutSessionUpdateRequest:
                components.CheckoutSessionUpdateRequest$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                checkout_session_id: "checkoutSessionId",
                CheckoutSessionUpdateRequest: "checkoutSessionUpdateRequest",
            });
        });

    export type Outbound = {
        checkout_session_id: string;
        CheckoutSessionUpdateRequest?:
            | components.CheckoutSessionUpdateRequest$.Outbound
            | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateCheckoutSessionRequest> = z
        .object({
            checkoutSessionId: z.string(),
            checkoutSessionUpdateRequest:
                components.CheckoutSessionUpdateRequest$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                checkoutSessionId: "checkout_session_id",
                checkoutSessionUpdateRequest: "CheckoutSessionUpdateRequest",
            });
        });
}
