/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type UpdateReportRequest = {
    /**
     * The unique ID for a report.
     */
    reportId: string;
    reportUpdate?: components.ReportUpdate | undefined;
};

/** @internal */
export namespace UpdateReportRequest$ {
    export const inboundSchema: z.ZodType<UpdateReportRequest, z.ZodTypeDef, unknown> = z
        .object({
            report_id: z.string(),
            ReportUpdate: components.ReportUpdate$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                report_id: "reportId",
                ReportUpdate: "reportUpdate",
            });
        });

    export type Outbound = {
        report_id: string;
        ReportUpdate?: components.ReportUpdate$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateReportRequest> = z
        .object({
            reportId: z.string(),
            reportUpdate: components.ReportUpdate$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                reportId: "report_id",
                reportUpdate: "ReportUpdate",
            });
        });
}
