/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateDigitalWalletGlobals = {
  merchantAccountId?: string | undefined;
};

export type UpdateDigitalWalletRequest = {
  /**
   * The ID of the digital wallet to edit.
   */
  digitalWalletId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  digitalWalletUpdate: components.DigitalWalletUpdate;
};

/** @internal */
export type UpdateDigitalWalletRequest$Outbound = {
  digital_wallet_id: string;
  merchantAccountId?: string | null | undefined;
  DigitalWalletUpdate: components.DigitalWalletUpdate$Outbound;
};

/** @internal */
export const UpdateDigitalWalletRequest$outboundSchema: z.ZodType<
  UpdateDigitalWalletRequest$Outbound,
  z.ZodTypeDef,
  UpdateDigitalWalletRequest
> = z.object({
  digitalWalletId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
  digitalWalletUpdate: components.DigitalWalletUpdate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    digitalWalletId: "digital_wallet_id",
    digitalWalletUpdate: "DigitalWalletUpdate",
  });
});

export function updateDigitalWalletRequestToJSON(
  updateDigitalWalletRequest: UpdateDigitalWalletRequest,
): string {
  return JSON.stringify(
    UpdateDigitalWalletRequest$outboundSchema.parse(updateDigitalWalletRequest),
  );
}
