/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateThreeDsScenarioGlobals = {
  merchantAccountId?: string | undefined;
};

export type UpdateThreeDsScenarioRequest = {
  /**
   * The ID of the 3DS scenario
   */
  threeDsScenarioId: string;
  /**
   * The ID of the merchant account to use for this request.
   */
  merchantAccountId?: string | null | undefined;
  threeDSecureScenarioUpdate: components.ThreeDSecureScenarioUpdate;
};

/** @internal */
export type UpdateThreeDsScenarioRequest$Outbound = {
  three_ds_scenario_id: string;
  merchantAccountId?: string | null | undefined;
  ThreeDSecureScenarioUpdate: components.ThreeDSecureScenarioUpdate$Outbound;
};

/** @internal */
export const UpdateThreeDsScenarioRequest$outboundSchema: z.ZodType<
  UpdateThreeDsScenarioRequest$Outbound,
  z.ZodTypeDef,
  UpdateThreeDsScenarioRequest
> = z.object({
  threeDsScenarioId: z.string(),
  merchantAccountId: z.nullable(z.string()).optional(),
  threeDSecureScenarioUpdate:
    components.ThreeDSecureScenarioUpdate$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    threeDsScenarioId: "three_ds_scenario_id",
    threeDSecureScenarioUpdate: "ThreeDSecureScenarioUpdate",
  });
});

export function updateThreeDsScenarioRequestToJSON(
  updateThreeDsScenarioRequest: UpdateThreeDsScenarioRequest,
): string {
  return JSON.stringify(
    UpdateThreeDsScenarioRequest$outboundSchema.parse(
      updateThreeDsScenarioRequest,
    ),
  );
}
