/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A request to create an Account Updater job.
 */
export type AccountUpdaterJobCreate = {
    /**
     * A list of unique payment method identifiers used to create the Account Updater job.
     *
     * @remarks
     * A payment method will be considered only if it qualifies for an inquiry.
     */
    paymentMethodIds: Array<string>;
};

/** @internal */
export namespace AccountUpdaterJobCreate$ {
    export type Inbound = {
        payment_method_ids: Array<string>;
    };

    export const inboundSchema: z.ZodType<AccountUpdaterJobCreate, z.ZodTypeDef, Inbound> = z
        .object({
            payment_method_ids: z.array(z.string()),
        })
        .transform((v) => {
            return {
                paymentMethodIds: v.payment_method_ids,
            };
        });

    export type Outbound = {
        payment_method_ids: Array<string>;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AccountUpdaterJobCreate> = z
        .object({
            paymentMethodIds: z.array(z.string()),
        })
        .transform((v) => {
            return {
                payment_method_ids: v.paymentMethodIds,
            };
        });
}
