/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { OpenEnum, Unrecognized } from "../../types/enums.js";

export const AdyenAutoRescueSepaScenariosEnum = {
  AutoRescueSuccessfulFirst: "AutoRescueSuccessfulFirst",
  AutoRescueSuccessfulSecond: "AutoRescueSuccessfulSecond",
  AutoRescueFailed: "AutoRescueFailed",
} as const;
export type AdyenAutoRescueSepaScenariosEnum = OpenEnum<
  typeof AdyenAutoRescueSepaScenariosEnum
>;

/** @internal */
export const AdyenAutoRescueSepaScenariosEnum$outboundSchema: z.ZodType<
  AdyenAutoRescueSepaScenariosEnum,
  z.ZodTypeDef,
  AdyenAutoRescueSepaScenariosEnum
> = z.union([
  z.nativeEnum(AdyenAutoRescueSepaScenariosEnum),
  z.string().and(z.custom<Unrecognized<string>>()),
]);
