/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AdyenSplitsOptions = {
  /**
   * Split payment values to pass to the Adyen API on payment authorization. See [the Adyen docs](https://docs.adyen.com/platforms/online-payments/split-transactions/split-payments-at-authorization/) for details on the format and contents of the list.
   */
  authorization?: Array<{ [k: string]: any }> | null | undefined;
  /**
   * Split payment values to pass to the Adyen API on payment capture. See [the Adyen docs](https://docs.adyen.com/platforms/online-payments/split-transactions/split-payments-at-capture/) for details on the format and contents of the list.
   */
  capture?: Array<{ [k: string]: any }> | null | undefined;
  /**
   * Split payment values to pass to the Adyen API on payment refund. See [the Adyen docs](https://docs.adyen.com/platforms/online-payments/split-transactions/split-refunds/) for details on the format and contents of the list.
   */
  refund?: Array<{ [k: string]: any }> | null | undefined;
};

/** @internal */
export type AdyenSplitsOptions$Outbound = {
  authorization?: Array<{ [k: string]: any }> | null | undefined;
  capture?: Array<{ [k: string]: any }> | null | undefined;
  refund?: Array<{ [k: string]: any }> | null | undefined;
};

/** @internal */
export const AdyenSplitsOptions$outboundSchema: z.ZodType<
  AdyenSplitsOptions$Outbound,
  z.ZodTypeDef,
  AdyenSplitsOptions
> = z.object({
  authorization: z.nullable(z.array(z.record(z.any()))).optional(),
  capture: z.nullable(z.array(z.record(z.any()))).optional(),
  refund: z.nullable(z.array(z.record(z.any()))).optional(),
});

export function adyenSplitsOptionsToJSON(
  adyenSplitsOptions: AdyenSplitsOptions,
): string {
  return JSON.stringify(
    AdyenSplitsOptions$outboundSchema.parse(adyenSplitsOptions),
  );
}
