/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

/**
 * `anti-fraud-service-definition`.
 */
export enum AntiFraudServiceDefinitionType {
    AntiFraudServiceDefinition = "anti-fraud-service-definition",
}

/**
 * Defines the type of input that needs to be rendered for this field.
 */
export enum AntiFraudServiceDefinitionFormat {
    Text = "text",
    Multiline = "multiline",
    Number = "number",
}

/**
 * A single field that needs to be submitted for a payment service when it
 *
 * @remarks
 * is created.
 */
export type AntiFraudServiceDefinitionFields = {
    /**
     * The key of a field that needs to be submitted.
     */
    key?: string | undefined;
    /**
     * The name to display for a field in the dashboard.
     */
    displayName?: string | undefined;
    /**
     * Defines if this field is required when the service is created.
     */
    required?: boolean | undefined;
    /**
     * Defines the type of input that needs to be rendered for this field.
     */
    format?: AntiFraudServiceDefinitionFormat | undefined;
    /**
     * Defines if this field is secret. When `true` the field is not
     *
     * @remarks
     * returned when querying the payment service.
     */
    secret?: boolean | undefined;
};

/**
 * An available anti fraud service that can be configured.
 */
export type AntiFraudServiceDefinition = {
    /**
     * The ID of the anti fraud service definition.
     */
    id?: string | undefined;
    /**
     * `anti-fraud-service-definition`.
     */
    type?: AntiFraudServiceDefinitionType | undefined;
    /**
     * The display name of this service.
     */
    displayName?: string | undefined;
    /**
     * A list of fields that need to be submitted when activating the payment. service.
     */
    fields?: Array<AntiFraudServiceDefinitionFields> | undefined;
    /**
     * An icon to display for the payment service.
     */
    iconUrl?: string | undefined;
};

/** @internal */
export namespace AntiFraudServiceDefinitionType$ {
    export const inboundSchema = z.nativeEnum(AntiFraudServiceDefinitionType);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace AntiFraudServiceDefinitionFormat$ {
    export const inboundSchema = z.nativeEnum(AntiFraudServiceDefinitionFormat);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace AntiFraudServiceDefinitionFields$ {
    export const inboundSchema: z.ZodType<AntiFraudServiceDefinitionFields, z.ZodTypeDef, unknown> =
        z
            .object({
                key: z.string().optional(),
                display_name: z.string().optional(),
                required: z.boolean().optional(),
                format: AntiFraudServiceDefinitionFormat$.inboundSchema.optional(),
                secret: z.boolean().optional(),
            })
            .transform((v) => {
                return remap$(v, {
                    display_name: "displayName",
                });
            });

    export type Outbound = {
        key?: string | undefined;
        display_name?: string | undefined;
        required?: boolean | undefined;
        format?: string | undefined;
        secret?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        AntiFraudServiceDefinitionFields
    > = z
        .object({
            key: z.string().optional(),
            displayName: z.string().optional(),
            required: z.boolean().optional(),
            format: AntiFraudServiceDefinitionFormat$.outboundSchema.optional(),
            secret: z.boolean().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                displayName: "display_name",
            });
        });
}

/** @internal */
export namespace AntiFraudServiceDefinition$ {
    export const inboundSchema: z.ZodType<AntiFraudServiceDefinition, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string().optional(),
            type: AntiFraudServiceDefinitionType$.inboundSchema.default(
                AntiFraudServiceDefinitionType.AntiFraudServiceDefinition
            ),
            display_name: z.string().optional(),
            fields: z
                .array(z.lazy(() => AntiFraudServiceDefinitionFields$.inboundSchema))
                .optional(),
            icon_url: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                display_name: "displayName",
                icon_url: "iconUrl",
            });
        });

    export type Outbound = {
        id?: string | undefined;
        type: string;
        display_name?: string | undefined;
        fields?: Array<AntiFraudServiceDefinitionFields$.Outbound> | undefined;
        icon_url?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AntiFraudServiceDefinition> = z
        .object({
            id: z.string().optional(),
            type: AntiFraudServiceDefinitionType$.outboundSchema.default(
                AntiFraudServiceDefinitionType.AntiFraudServiceDefinition
            ),
            displayName: z.string().optional(),
            fields: z
                .array(z.lazy(() => AntiFraudServiceDefinitionFields$.outboundSchema))
                .optional(),
            iconUrl: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                displayName: "display_name",
                iconUrl: "icon_url",
            });
        });
}
