/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ApiCommonSchemasMerchantAccount,
  ApiCommonSchemasMerchantAccount$inboundSchema,
} from "./apicommonschemasmerchantaccount.js";
import {
  ApiRoutersApiKeyPairsSchemasCreator,
  ApiRoutersApiKeyPairsSchemasCreator$inboundSchema,
} from "./apiroutersapikeypairsschemascreator.js";
import {
  CertificateAlgorithm,
  CertificateAlgorithm$inboundSchema,
} from "./certificatealgorithm.js";
import { Role, Role$inboundSchema } from "./role.js";

export type APIKeyPair = {
  /**
   * The type of this resource.
   */
  type: "api-key-pair";
  /**
   * The ID for the API key pair.
   */
  id: string;
  /**
   * The unique thumbprint that identifies the API key pair.
   */
  thumbprint: string;
  /**
   * The display name for the API key pair.
   */
  displayName: string;
  algorithm: CertificateAlgorithm;
  /**
   * Whether the API key pair is active and can be used to authenticate.
   */
  active: boolean;
  /**
   * The PEM-encoded private key. Only returned once, in the response to creating the API key pair, and only when Gr4vy generated the key pair. Store it securely, as it cannot be retrieved later.
   */
  privateKey?: string | null | undefined;
  /**
   * The date and time when this API key pair was created.
   */
  createdAt: Date;
  /**
   * The date and time when this API key pair was last updated.
   */
  updatedAt: Date;
  /**
   * The user or API key pair that created this API key pair.
   */
  creator?: ApiRoutersApiKeyPairsSchemasCreator | null | undefined;
  /**
   * The merchant accounts this API key pair has access to. An empty list means it has access to all merchant accounts.
   */
  merchantAccounts?: Array<ApiCommonSchemasMerchantAccount> | undefined;
  /**
   * The roles assigned to this API key pair.
   */
  roles?: Array<Role> | undefined;
};

/** @internal */
export const APIKeyPair$inboundSchema: z.ZodType<
  APIKeyPair,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("api-key-pair").default("api-key-pair"),
  id: z.string(),
  thumbprint: z.string(),
  display_name: z.string(),
  algorithm: CertificateAlgorithm$inboundSchema,
  active: z.boolean(),
  private_key: z.nullable(z.string()).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  creator: z.nullable(ApiRoutersApiKeyPairsSchemasCreator$inboundSchema)
    .optional(),
  merchant_accounts: z.array(ApiCommonSchemasMerchantAccount$inboundSchema)
    .optional(),
  roles: z.array(Role$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
    "private_key": "privateKey",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "merchant_accounts": "merchantAccounts",
  });
});

export function apiKeyPairFromJSON(
  jsonString: string,
): SafeParseResult<APIKeyPair, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => APIKeyPair$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'APIKeyPair' from JSON`,
  );
}
