/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ApiLog, ApiLog$ } from "./apilog";
import * as z from "zod";

/**
 * A list of API log entries.
 */
export type ApiLogs = {
    /**
     * A list of API log entries.
     */
    items?: Array<ApiLog> | undefined;
};

/** @internal */
export namespace ApiLogs$ {
    export const inboundSchema: z.ZodType<ApiLogs, z.ZodTypeDef, unknown> = z.object({
        items: z.array(ApiLog$.inboundSchema).optional(),
    });

    export type Outbound = {
        items?: Array<ApiLog$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ApiLogs> = z.object({
        items: z.array(ApiLog$.outboundSchema).optional(),
    });
}
