/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const CancelStatus = {
  Succeeded: "succeeded",
  Pending: "pending",
  Failed: "failed",
} as const;
export type CancelStatus = OpenEnum<typeof CancelStatus>;

/** @internal */
export const CancelStatus$inboundSchema: z.ZodType<
  CancelStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CancelStatus);
