/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const CardType = {
  Credit: "credit",
  Debit: "debit",
  Prepaid: "prepaid",
} as const;
export type CardType = OpenEnum<typeof CardType>;

/** @internal */
export const CardType$inboundSchema: z.ZodType<
  CardType,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CardType);
