/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const CertificateAlgorithm = {
  Ecdsa: "ECDSA",
  Rsa: "RSA",
} as const;
export type CertificateAlgorithm = OpenEnum<typeof CertificateAlgorithm>;

/** @internal */
export const CertificateAlgorithm$inboundSchema: z.ZodType<
  CertificateAlgorithm,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(CertificateAlgorithm);
/** @internal */
export const CertificateAlgorithm$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  CertificateAlgorithm
> = openEnums.outboundSchema(CertificateAlgorithm);
