/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

/**
 * `id`.
 */
export enum CheckoutSessionFieldsIdPaymentMethodMethod {
    Id = "id",
}

/**
 * Details to use a stored card payment method.
 */
export type CheckoutSessionFieldsIdPaymentMethod = {
    /**
     * `id`.
     */
    method: CheckoutSessionFieldsIdPaymentMethodMethod;
    /**
     * The unique ID of the payment method.
     */
    id: string;
    /**
     * The 3 or 4 digit security code often found on the card. This often
     *
     * @remarks
     * referred to as the CVV or CVD.
     *
     * The security code can only be set if the stored payment method
     * represents a card.
     */
    securityCode?: string | undefined;
};

/** @internal */
export namespace CheckoutSessionFieldsIdPaymentMethodMethod$ {
    export const inboundSchema = z.nativeEnum(CheckoutSessionFieldsIdPaymentMethodMethod);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace CheckoutSessionFieldsIdPaymentMethod$ {
    export const inboundSchema: z.ZodType<
        CheckoutSessionFieldsIdPaymentMethod,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            method: CheckoutSessionFieldsIdPaymentMethodMethod$.inboundSchema,
            id: z.string(),
            security_code: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                security_code: "securityCode",
            });
        });

    export type Outbound = {
        method: string;
        id: string;
        security_code?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CheckoutSessionFieldsIdPaymentMethod
    > = z
        .object({
            method: CheckoutSessionFieldsIdPaymentMethodMethod$.outboundSchema,
            id: z.string(),
            securityCode: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                securityCode: "security_code",
            });
        });
}
