/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as z from "zod";

/**
 * `card`.
 */
export enum CheckoutSessionFieldsCardPaymentMethodMethod {
    Card = "card",
}

/**
 * Details to store a new card payment method.
 */
export type CheckoutSessionFieldsCardPaymentMethod = {
    /**
     * `card`.
     */
    method: CheckoutSessionFieldsCardPaymentMethodMethod;
    /**
     * The 13-19 digit number for this card as it can be found on the
     *
     * @remarks
     * front of the card.
     */
    number?: string | undefined;
    /**
     * The expiration date of the card, formatted `MM/YY`.
     */
    expirationDate?: string | undefined;
    /**
     * The 3 or 4 digit security code often found on the card. This often
     *
     * @remarks
     * referred to as the CVV or CVD.
     *
     * The security code can only be set if the stored payment method
     * represents a card.
     */
    securityCode?: string | undefined;
};

/** @internal */
export namespace CheckoutSessionFieldsCardPaymentMethodMethod$ {
    export const inboundSchema = z.nativeEnum(CheckoutSessionFieldsCardPaymentMethodMethod);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace CheckoutSessionFieldsCardPaymentMethod$ {
    export const inboundSchema: z.ZodType<
        CheckoutSessionFieldsCardPaymentMethod,
        z.ZodTypeDef,
        unknown
    > = z
        .object({
            method: CheckoutSessionFieldsCardPaymentMethodMethod$.inboundSchema,
            number: z.string().optional(),
            expiration_date: z.string().optional(),
            security_code: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                expiration_date: "expirationDate",
                security_code: "securityCode",
            });
        });

    export type Outbound = {
        method: string;
        number?: string | undefined;
        expiration_date?: string | undefined;
        security_code?: string | undefined;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CheckoutSessionFieldsCardPaymentMethod
    > = z
        .object({
            method: CheckoutSessionFieldsCardPaymentMethodMethod$.outboundSchema,
            number: z.string().optional(),
            expirationDate: z.string().optional(),
            securityCode: z.string().optional(),
        })
        .transform((v) => {
            return remap$(v, {
                expirationDate: "expiration_date",
                securityCode: "security_code",
            });
        });
}
