/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ClickToPaySession = {
    /**
     * The ID of the Digital Payment Application for Click to Pay.
     */
    digitalPaymentApplicationId?: string | undefined;
    /**
     * The name of the Digital Payment Application for Click to Pay.
     */
    digitalPaymentApplicationName?: string | undefined;
};

/** @internal */
export namespace ClickToPaySession$ {
    export type Inbound = {
        digital_payment_application_id?: string | undefined;
        digital_payment_application_name?: string | undefined;
    };

    export const inboundSchema: z.ZodType<ClickToPaySession, z.ZodTypeDef, Inbound> = z
        .object({
            digital_payment_application_id: z.string().optional(),
            digital_payment_application_name: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.digital_payment_application_id === undefined
                    ? null
                    : { digitalPaymentApplicationId: v.digital_payment_application_id }),
                ...(v.digital_payment_application_name === undefined
                    ? null
                    : { digitalPaymentApplicationName: v.digital_payment_application_name }),
            };
        });

    export type Outbound = {
        digital_payment_application_id?: string | undefined;
        digital_payment_application_name?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ClickToPaySession> = z
        .object({
            digitalPaymentApplicationId: z.string().optional(),
            digitalPaymentApplicationName: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.digitalPaymentApplicationId === undefined
                    ? null
                    : { digital_payment_application_id: v.digitalPaymentApplicationId }),
                ...(v.digitalPaymentApplicationName === undefined
                    ? null
                    : { digital_payment_application_name: v.digitalPaymentApplicationName }),
            };
        });
}
