/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ConnectionDefinition, ConnectionDefinition$ } from "./connectiondefinition";
import * as z from "zod";

/**
 * A list of available connection definitions.
 */
export type ConnectionDefinitions = {
    items?: Array<ConnectionDefinition> | undefined;
};

/** @internal */
export namespace ConnectionDefinitions$ {
    export const inboundSchema: z.ZodType<ConnectionDefinitions, z.ZodTypeDef, unknown> = z.object({
        items: z.array(ConnectionDefinition$.inboundSchema).optional(),
    });

    export type Outbound = {
        items?: Array<ConnectionDefinition$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectionDefinitions> =
        z.object({
            items: z.array(ConnectionDefinition$.outboundSchema).optional(),
        });
}
