/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Domain name for a digital wallet.
 */
export type DigitalWalletDomain = {
    /**
     * The domain name that a digital wallet can be used on. To use a
     *
     * @remarks
     * digital wallet on a website, the domain of the site is required to be
     * in this list.
     */
    domainName: string;
};

/** @internal */
export namespace DigitalWalletDomain$ {
    export type Inbound = {
        domain_name: string;
    };

    export const inboundSchema: z.ZodType<DigitalWalletDomain, z.ZodTypeDef, Inbound> = z
        .object({
            domain_name: z.string(),
        })
        .transform((v) => {
            return {
                domainName: v.domain_name,
            };
        });

    export type Outbound = {
        domain_name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DigitalWalletDomain> = z
        .object({
            domainName: z.string(),
        })
        .transform((v) => {
            return {
                domain_name: v.domainName,
            };
        });
}
