/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Always `digital-wallet`.
 */
export const DigitalWalletType = {
  DigitalWallet: "digital-wallet",
} as const;
/**
 * Always `digital-wallet`.
 */
export type DigitalWalletType = ClosedEnum<typeof DigitalWalletType>;

/**
 * The name of the digital wallet provider.
 */
export const DigitalWalletDigitalWalletProvider = {
  Apple: "apple",
  Google: "google",
  ClickToPay: "click-to-pay",
} as const;
/**
 * The name of the digital wallet provider.
 */
export type DigitalWalletDigitalWalletProvider = ClosedEnum<
  typeof DigitalWalletDigitalWalletProvider
>;

/**
 * Custom attributes for some digital wallets. Currently only used by Click to Pay.
 */
export type Fields = {};

/**
 * Base model with JSON encoders.
 */
export type DigitalWallet = {
  /**
   * Always `digital-wallet`.
   */
  type?: DigitalWalletType | undefined;
  /**
   * The ID for the digital wallet.
   */
  id: string;
  /**
   * The ID of the merchant account this digital wallet belongs to.
   */
  merchantAccountId: string;
  /**
   * The name of the digital wallet provider.
   */
  provider: DigitalWalletDigitalWalletProvider;
  /**
   * The name of the merchant the digital wallet is registered to.
   */
  merchantName: string;
  /**
   * The consumer facing name of the merchant.
   */
  merchantDisplayName?: string | undefined;
  /**
   * The main URL of the merchant.
   */
  merchantUrl?: string | undefined;
  /**
   * The country code where the merchant is registered.
   */
  merchantCountryCode?: string | undefined;
  /**
   * The list of domain names that a digital wallet can be used on (deprecated).
   */
  domainNames: Array<string>;
  /**
   * The number of active custom certificates registered for this digital wallet (Apple Pay only).
   */
  activeCertificateCount?: number | undefined;
  /**
   * The number of pending custom certificates registered for this digital wallet (Apple Pay only).
   */
  pendingCertificateCount?: number | undefined;
  /**
   * The number of expired custom certificates registered for this digital wallet (Apple Pay only).
   */
  expiredCertificateCount?: number | undefined;
  /**
   * Custom attributes for some digital wallets. Currently only used by Click to Pay.
   */
  fields?: Fields | undefined;
  /**
   * The date this buyer was created at.
   */
  createdAt: Date;
  /**
   * The date this buyer was last updated at.
   */
  updatedAt: Date;
};

/** @internal */
export const DigitalWalletType$inboundSchema: z.ZodNativeEnum<
  typeof DigitalWalletType
> = z.nativeEnum(DigitalWalletType);

/** @internal */
export const DigitalWalletType$outboundSchema: z.ZodNativeEnum<
  typeof DigitalWalletType
> = DigitalWalletType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DigitalWalletType$ {
  /** @deprecated use `DigitalWalletType$inboundSchema` instead. */
  export const inboundSchema = DigitalWalletType$inboundSchema;
  /** @deprecated use `DigitalWalletType$outboundSchema` instead. */
  export const outboundSchema = DigitalWalletType$outboundSchema;
}

/** @internal */
export const DigitalWalletDigitalWalletProvider$inboundSchema: z.ZodNativeEnum<
  typeof DigitalWalletDigitalWalletProvider
> = z.nativeEnum(DigitalWalletDigitalWalletProvider);

/** @internal */
export const DigitalWalletDigitalWalletProvider$outboundSchema: z.ZodNativeEnum<
  typeof DigitalWalletDigitalWalletProvider
> = DigitalWalletDigitalWalletProvider$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DigitalWalletDigitalWalletProvider$ {
  /** @deprecated use `DigitalWalletDigitalWalletProvider$inboundSchema` instead. */
  export const inboundSchema = DigitalWalletDigitalWalletProvider$inboundSchema;
  /** @deprecated use `DigitalWalletDigitalWalletProvider$outboundSchema` instead. */
  export const outboundSchema =
    DigitalWalletDigitalWalletProvider$outboundSchema;
}

/** @internal */
export const Fields$inboundSchema: z.ZodType<Fields, z.ZodTypeDef, unknown> = z
  .object({});

/** @internal */
export type Fields$Outbound = {};

/** @internal */
export const Fields$outboundSchema: z.ZodType<
  Fields$Outbound,
  z.ZodTypeDef,
  Fields
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Fields$ {
  /** @deprecated use `Fields$inboundSchema` instead. */
  export const inboundSchema = Fields$inboundSchema;
  /** @deprecated use `Fields$outboundSchema` instead. */
  export const outboundSchema = Fields$outboundSchema;
  /** @deprecated use `Fields$Outbound` instead. */
  export type Outbound = Fields$Outbound;
}

export function fieldsToJSON(fields: Fields): string {
  return JSON.stringify(Fields$outboundSchema.parse(fields));
}

export function fieldsFromJSON(
  jsonString: string,
): SafeParseResult<Fields, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fields$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fields' from JSON`,
  );
}

/** @internal */
export const DigitalWallet$inboundSchema: z.ZodType<
  DigitalWallet,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: DigitalWalletType$inboundSchema.default("digital-wallet"),
  id: z.string(),
  merchant_account_id: z.string(),
  provider: DigitalWalletDigitalWalletProvider$inboundSchema,
  merchant_name: z.string(),
  merchant_display_name: z.string().optional(),
  merchant_url: z.string().optional(),
  merchant_country_code: z.string().optional(),
  domain_names: z.array(z.string()),
  active_certificate_count: z.number().int().default(0),
  pending_certificate_count: z.number().int().default(0),
  expired_certificate_count: z.number().int().default(0),
  fields: z.lazy(() => Fields$inboundSchema).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "merchant_account_id": "merchantAccountId",
    "merchant_name": "merchantName",
    "merchant_display_name": "merchantDisplayName",
    "merchant_url": "merchantUrl",
    "merchant_country_code": "merchantCountryCode",
    "domain_names": "domainNames",
    "active_certificate_count": "activeCertificateCount",
    "pending_certificate_count": "pendingCertificateCount",
    "expired_certificate_count": "expiredCertificateCount",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
  });
});

/** @internal */
export type DigitalWallet$Outbound = {
  type: string;
  id: string;
  merchant_account_id: string;
  provider: string;
  merchant_name: string;
  merchant_display_name?: string | undefined;
  merchant_url?: string | undefined;
  merchant_country_code?: string | undefined;
  domain_names: Array<string>;
  active_certificate_count: number;
  pending_certificate_count: number;
  expired_certificate_count: number;
  fields?: Fields$Outbound | undefined;
  created_at: string;
  updated_at: string;
};

/** @internal */
export const DigitalWallet$outboundSchema: z.ZodType<
  DigitalWallet$Outbound,
  z.ZodTypeDef,
  DigitalWallet
> = z.object({
  type: DigitalWalletType$outboundSchema.default("digital-wallet"),
  id: z.string(),
  merchantAccountId: z.string(),
  provider: DigitalWalletDigitalWalletProvider$outboundSchema,
  merchantName: z.string(),
  merchantDisplayName: z.string().optional(),
  merchantUrl: z.string().optional(),
  merchantCountryCode: z.string().optional(),
  domainNames: z.array(z.string()),
  activeCertificateCount: z.number().int().default(0),
  pendingCertificateCount: z.number().int().default(0),
  expiredCertificateCount: z.number().int().default(0),
  fields: z.lazy(() => Fields$outboundSchema).optional(),
  createdAt: z.date().transform(v => v.toISOString()),
  updatedAt: z.date().transform(v => v.toISOString()),
}).transform((v) => {
  return remap$(v, {
    merchantAccountId: "merchant_account_id",
    merchantName: "merchant_name",
    merchantDisplayName: "merchant_display_name",
    merchantUrl: "merchant_url",
    merchantCountryCode: "merchant_country_code",
    domainNames: "domain_names",
    activeCertificateCount: "active_certificate_count",
    pendingCertificateCount: "pending_certificate_count",
    expiredCertificateCount: "expired_certificate_count",
    createdAt: "created_at",
    updatedAt: "updated_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DigitalWallet$ {
  /** @deprecated use `DigitalWallet$inboundSchema` instead. */
  export const inboundSchema = DigitalWallet$inboundSchema;
  /** @deprecated use `DigitalWallet$outboundSchema` instead. */
  export const outboundSchema = DigitalWallet$outboundSchema;
  /** @deprecated use `DigitalWallet$Outbound` instead. */
  export type Outbound = DigitalWallet$Outbound;
}

export function digitalWalletToJSON(digitalWallet: DigitalWallet): string {
  return JSON.stringify(DigitalWallet$outboundSchema.parse(digitalWallet));
}

export function digitalWalletFromJSON(
  jsonString: string,
): SafeParseResult<DigitalWallet, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DigitalWallet$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DigitalWallet' from JSON`,
  );
}
