/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ForterAntiFraudOptionsCartItemBeneficiaryComments = {
  /**
   * Comments from the user to the merchant.
   */
  userCommentsToMerchant?: string | null | undefined;
  /**
   * Message intended for the beneficiary of the item.
   */
  messageToBeneficiary?: string | null | undefined;
  /**
   * Comments from the merchant about this transaction.
   */
  merchantComments?: string | null | undefined;
};

/** @internal */
export type ForterAntiFraudOptionsCartItemBeneficiaryComments$Outbound = {
  user_comments_to_merchant?: string | null | undefined;
  message_to_beneficiary?: string | null | undefined;
  merchant_comments?: string | null | undefined;
};

/** @internal */
export const ForterAntiFraudOptionsCartItemBeneficiaryComments$outboundSchema:
  z.ZodType<
    ForterAntiFraudOptionsCartItemBeneficiaryComments$Outbound,
    z.ZodTypeDef,
    ForterAntiFraudOptionsCartItemBeneficiaryComments
  > = z.object({
    userCommentsToMerchant: z.nullable(z.string()).optional(),
    messageToBeneficiary: z.nullable(z.string()).optional(),
    merchantComments: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      userCommentsToMerchant: "user_comments_to_merchant",
      messageToBeneficiary: "message_to_beneficiary",
      merchantComments: "merchant_comments",
    });
  });

export function forterAntiFraudOptionsCartItemBeneficiaryCommentsToJSON(
  forterAntiFraudOptionsCartItemBeneficiaryComments:
    ForterAntiFraudOptionsCartItemBeneficiaryComments,
): string {
  return JSON.stringify(
    ForterAntiFraudOptionsCartItemBeneficiaryComments$outboundSchema.parse(
      forterAntiFraudOptionsCartItemBeneficiaryComments,
    ),
  );
}
