/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ForterAntiFraudOptionsDiscountCouponDiscountAmount = {
  /**
   * The discount amount in USD.
   */
  amountUsd?: string | null | undefined;
  /**
   * The discount amount in local currency.
   */
  amountLocalCurrency?: string | null | undefined;
  /**
   * The currency code for the discount amount.
   */
  currency?: string | null | undefined;
};

/** @internal */
export type ForterAntiFraudOptionsDiscountCouponDiscountAmount$Outbound = {
  amount_usd?: string | null | undefined;
  amount_local_currency?: string | null | undefined;
  currency?: string | null | undefined;
};

/** @internal */
export const ForterAntiFraudOptionsDiscountCouponDiscountAmount$outboundSchema:
  z.ZodType<
    ForterAntiFraudOptionsDiscountCouponDiscountAmount$Outbound,
    z.ZodTypeDef,
    ForterAntiFraudOptionsDiscountCouponDiscountAmount
  > = z.object({
    amountUsd: z.nullable(z.string()).optional(),
    amountLocalCurrency: z.nullable(z.string()).optional(),
    currency: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      amountUsd: "amount_usd",
      amountLocalCurrency: "amount_local_currency",
    });
  });

export function forterAntiFraudOptionsDiscountCouponDiscountAmountToJSON(
  forterAntiFraudOptionsDiscountCouponDiscountAmount:
    ForterAntiFraudOptionsDiscountCouponDiscountAmount,
): string {
  return JSON.stringify(
    ForterAntiFraudOptionsDiscountCouponDiscountAmount$outboundSchema.parse(
      forterAntiFraudOptionsDiscountCouponDiscountAmount,
    ),
  );
}
