/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { catchUnrecognizedEnum, OpenEnum } from "../../types/enums.js";

export const GiftCardServiceProvider = {
  MockGiftCard: "mock-gift-card",
  QwikcilverGiftCard: "qwikcilver-gift-card",
} as const;
export type GiftCardServiceProvider = OpenEnum<typeof GiftCardServiceProvider>;

/** @internal */
export const GiftCardServiceProvider$inboundSchema: z.ZodType<
  GiftCardServiceProvider,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(GiftCardServiceProvider),
    z.string().transform(catchUnrecognizedEnum),
  ]);
