/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The number and pin for a gift card to fetch a balance for.
 */
export type GiftCardRequest = {
  /**
   * The 16-19 digit number for the gift card.
   */
  number: string;
  /**
   * The PIN for this gift card.
   */
  pin: string;
};

/** @internal */
export type GiftCardRequest$Outbound = {
  number: string;
  pin: string;
};

/** @internal */
export const GiftCardRequest$outboundSchema: z.ZodType<
  GiftCardRequest$Outbound,
  z.ZodTypeDef,
  GiftCardRequest
> = z.object({
  number: z.string(),
  pin: z.string(),
});

export function giftCardRequestToJSON(
  giftCardRequest: GiftCardRequest,
): string {
  return JSON.stringify(GiftCardRequest$outboundSchema.parse(giftCardRequest));
}
