/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const GiftCardRedemptionStatus = {
  Created: "created",
  Succeeded: "succeeded",
  Failed: "failed",
  Skipped: "skipped",
} as const;
export type GiftCardRedemptionStatus = OpenEnum<
  typeof GiftCardRedemptionStatus
>;

/** @internal */
export const GiftCardRedemptionStatus$inboundSchema: z.ZodType<
  GiftCardRedemptionStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(GiftCardRedemptionStatus);
