/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { GiftCardBalanceNewRequest, GiftCardBalanceNewRequest$ } from "./giftcardbalancenewrequest";
import {
    GiftCardBalanceStoredRequest,
    GiftCardBalanceStoredRequest$,
} from "./giftcardbalancestoredrequest";
import * as z from "zod";

export type GiftCardBalancesRequestItems = GiftCardBalanceStoredRequest | GiftCardBalanceNewRequest;

/**
 * A request to check the balance for a set of stored and
 *
 * @remarks
 * non-stored gift cards.
 */
export type GiftCardBalancesRequest = {
    /**
     * One or more gift cards to check balances for, up to a default limit
     *
     * @remarks
     * of 10 gift cards. Please contact our team to change this limit.
     */
    items?: Array<GiftCardBalanceStoredRequest | GiftCardBalanceNewRequest> | undefined;
};

/** @internal */
export namespace GiftCardBalancesRequestItems$ {
    export const inboundSchema: z.ZodType<GiftCardBalancesRequestItems, z.ZodTypeDef, unknown> =
        z.union([
            GiftCardBalanceStoredRequest$.inboundSchema,
            GiftCardBalanceNewRequest$.inboundSchema,
        ]);

    export type Outbound =
        | GiftCardBalanceStoredRequest$.Outbound
        | GiftCardBalanceNewRequest$.Outbound;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GiftCardBalancesRequestItems> =
        z.union([
            GiftCardBalanceStoredRequest$.outboundSchema,
            GiftCardBalanceNewRequest$.outboundSchema,
        ]);
}

/** @internal */
export namespace GiftCardBalancesRequest$ {
    export const inboundSchema: z.ZodType<GiftCardBalancesRequest, z.ZodTypeDef, unknown> =
        z.object({
            items: z
                .array(
                    z.union([
                        GiftCardBalanceStoredRequest$.inboundSchema,
                        GiftCardBalanceNewRequest$.inboundSchema,
                    ])
                )
                .optional(),
        });

    export type Outbound = {
        items?:
            | Array<GiftCardBalanceStoredRequest$.Outbound | GiftCardBalanceNewRequest$.Outbound>
            | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GiftCardBalancesRequest> =
        z.object({
            items: z
                .array(
                    z.union([
                        GiftCardBalanceStoredRequest$.outboundSchema,
                        GiftCardBalanceNewRequest$.outboundSchema,
                    ])
                )
                .optional(),
        });
}
