/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Gift card error codes.
 *
 * @remarks
 *
 * Gr4vy normalised gift card error codes. Keep the naming and style in line with
 * those in the connectors framework.
 *
 * If new codes are added, append them at the end or amend public simulator
 * documentation: https://docs.gr4vy.com/guides/features/gift-cards/simulator
 */
export const GiftCardErrorCode = {
  InvalidGiftCard: "invalid_gift_card",
  ExpiredCard: "expired_card",
  InactiveCard: "inactive_card",
  InvalidServiceCredentials: "invalid_service_credentials",
  InvalidAmount: "invalid_amount",
  IncorrectCurrency: "incorrect_currency",
  InsufficientFunds: "insufficient_funds",
  InvalidServiceConfiguration: "invalid_service_configuration",
  OperationCanceled: "operation_canceled",
  ServiceError: "service_error",
  ServiceNetworkError: "service_network_error",
  UnknownError: "unknown_error",
  MaxGiftCardsReached: "max_gift_cards_reached",
} as const;
/**
 * Gift card error codes.
 *
 * @remarks
 *
 * Gr4vy normalised gift card error codes. Keep the naming and style in line with
 * those in the connectors framework.
 *
 * If new codes are added, append them at the end or amend public simulator
 * documentation: https://docs.gr4vy.com/guides/features/gift-cards/simulator
 */
export type GiftCardErrorCode = OpenEnum<typeof GiftCardErrorCode>;

/** @internal */
export const GiftCardErrorCode$inboundSchema: z.ZodType<
  GiftCardErrorCode,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(GiftCardErrorCode);
