/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * The ID of a stored gift card to fetch a balance for.
 */
export type GiftCardStoredRequest = {
  /**
   * The ID of the field to fetch a balance for.
   */
  id: string;
};

/** @internal */
export type GiftCardStoredRequest$Outbound = {
  id: string;
};

/** @internal */
export const GiftCardStoredRequest$outboundSchema: z.ZodType<
  GiftCardStoredRequest$Outbound,
  z.ZodTypeDef,
  GiftCardStoredRequest
> = z.object({
  id: z.string(),
});

export function giftCardStoredRequestToJSON(
  giftCardStoredRequest: GiftCardStoredRequest,
): string {
  return JSON.stringify(
    GiftCardStoredRequest$outboundSchema.parse(giftCardStoredRequest),
  );
}
