/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type MerchantProfileScheme = {
  /**
   * Acquirer BIN to use when calling 3DS through this scheme.
   */
  merchantAcquirerBin: string;
  /**
   * Merchant ID to use when calling 3DS through this scheme.
   */
  merchantAcquirerId: string;
  merchantName: string;
  /**
   * The merchant's ISO 3166-1 numeric country code.
   */
  merchantCountryCode: string;
  /**
   * Merchant category code to use when calling 3DS through this scheme.
   */
  merchantCategoryCode: string;
  /**
   * URL to send when calling 3DS through this scheme.
   */
  merchantUrl: string;
};

/** @internal */
export type MerchantProfileScheme$Outbound = {
  merchant_acquirer_bin: string;
  merchant_acquirer_id: string;
  merchant_name: string;
  merchant_country_code: string;
  merchant_category_code: string;
  merchant_url: string;
};

/** @internal */
export const MerchantProfileScheme$outboundSchema: z.ZodType<
  MerchantProfileScheme$Outbound,
  z.ZodTypeDef,
  MerchantProfileScheme
> = z.object({
  merchantAcquirerBin: z.string(),
  merchantAcquirerId: z.string(),
  merchantName: z.string(),
  merchantCountryCode: z.string(),
  merchantCategoryCode: z.string(),
  merchantUrl: z.string(),
}).transform((v) => {
  return remap$(v, {
    merchantAcquirerBin: "merchant_acquirer_bin",
    merchantAcquirerId: "merchant_acquirer_id",
    merchantName: "merchant_name",
    merchantCountryCode: "merchant_country_code",
    merchantCategoryCode: "merchant_category_code",
    merchantUrl: "merchant_url",
  });
});

export function merchantProfileSchemeToJSON(
  merchantProfileScheme: MerchantProfileScheme,
): string {
  return JSON.stringify(
    MerchantProfileScheme$outboundSchema.parse(merchantProfileScheme),
  );
}
