/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  catchUnrecognizedEnum,
  OpenEnum,
  Unrecognized,
} from "../../types/enums.js";

export const PaymentMethodStatus = {
  Processing: "processing",
  BuyerApprovalRequired: "buyer_approval_required",
  Succeeded: "succeeded",
  Failed: "failed",
  Paused: "paused",
} as const;
export type PaymentMethodStatus = OpenEnum<typeof PaymentMethodStatus>;

/** @internal */
export const PaymentMethodStatus$inboundSchema: z.ZodType<
  PaymentMethodStatus,
  z.ZodTypeDef,
  unknown
> = z
  .union([
    z.nativeEnum(PaymentMethodStatus),
    z.string().transform(catchUnrecognizedEnum),
  ]);
/** @internal */
export const PaymentMethodStatus$outboundSchema: z.ZodType<
  PaymentMethodStatus,
  z.ZodTypeDef,
  PaymentMethodStatus
> = z.union([
  z.nativeEnum(PaymentMethodStatus),
  z.string().and(z.custom<Unrecognized<string>>()),
]);
