/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const PaymentServiceStatus = {
  Pending: "pending",
  Created: "created",
  Failed: "failed",
} as const;
export type PaymentServiceStatus = OpenEnum<typeof PaymentServiceStatus>;

/** @internal */
export const PaymentServiceStatus$inboundSchema: z.ZodType<
  PaymentServiceStatus,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(PaymentServiceStatus);
