/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { PaymentMethodTokenized, PaymentMethodTokenized$ } from "./paymentmethodtokenized";
import * as z from "zod";

/**
 * A list of stored payment methods in summarized format.
 */
export type PaymentMethodsTokenized = {
    /**
     * A list of stored payment methods in summarized format.
     */
    items?: Array<PaymentMethodTokenized> | undefined;
};

/** @internal */
export namespace PaymentMethodsTokenized$ {
    export const inboundSchema: z.ZodType<PaymentMethodsTokenized, z.ZodTypeDef, unknown> =
        z.object({
            items: z.array(PaymentMethodTokenized$.inboundSchema).optional(),
        });

    export type Outbound = {
        items?: Array<PaymentMethodTokenized$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PaymentMethodsTokenized> =
        z.object({
            items: z.array(PaymentMethodTokenized$.outboundSchema).optional(),
        });
}
