/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PaymentMethod, PaymentMethod$inboundSchema } from "./paymentmethod.js";

export type PaymentMethods = {
  /**
   * A list of items returned for this request.
   */
  items: Array<PaymentMethod>;
  /**
   * The number of items for this page.
   */
  limit?: number | undefined;
  /**
   * The cursor pointing at the next page of items.
   */
  nextCursor?: string | null | undefined;
  /**
   * The cursor pointing at the previous page of items.
   */
  previousCursor?: string | null | undefined;
};

/** @internal */
export const PaymentMethods$inboundSchema: z.ZodType<
  PaymentMethods,
  z.ZodTypeDef,
  unknown
> = z.object({
  items: z.array(PaymentMethod$inboundSchema),
  limit: z.number().int().default(20),
  next_cursor: z.nullable(z.string()).optional(),
  previous_cursor: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "next_cursor": "nextCursor",
    "previous_cursor": "previousCursor",
  });
});

export function paymentMethodsFromJSON(
  jsonString: string,
): SafeParseResult<PaymentMethods, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentMethods$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentMethods' from JSON`,
  );
}
