/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  PaypalOrderUpdateCallbackConfig,
  PaypalOrderUpdateCallbackConfig$Outbound,
  PaypalOrderUpdateCallbackConfig$outboundSchema,
} from "./paypalorderupdatecallbackconfig.js";
import {
  PaypalShippingOptions,
  PaypalShippingOptions$Outbound,
  PaypalShippingOptions$outboundSchema,
} from "./paypalshippingoptions.js";

export type PaypalOptions = {
  /**
   * Configuration for server-side callbacks during the PayPal checkout flow.
   */
  orderUpdateCallbackConfig?:
    | PaypalOrderUpdateCallbackConfig
    | null
    | undefined;
  /**
   * Additional Set Transaction Context Values (STC) to be sent to PayPal as part of the transaction.
   */
  additionalData?: Array<{ [k: string]: string }> | null | undefined;
  /**
   * Shipping information to be passed to the PayPal API.
   */
  shipping?: PaypalShippingOptions | null | undefined;
};

/** @internal */
export type PaypalOptions$Outbound = {
  order_update_callback_config?:
    | PaypalOrderUpdateCallbackConfig$Outbound
    | null
    | undefined;
  additional_data?: Array<{ [k: string]: string }> | null | undefined;
  shipping?: PaypalShippingOptions$Outbound | null | undefined;
};

/** @internal */
export const PaypalOptions$outboundSchema: z.ZodType<
  PaypalOptions$Outbound,
  z.ZodTypeDef,
  PaypalOptions
> = z.object({
  orderUpdateCallbackConfig: z.nullable(
    PaypalOrderUpdateCallbackConfig$outboundSchema,
  ).optional(),
  additionalData: z.nullable(z.array(z.record(z.string()))).optional(),
  shipping: z.nullable(PaypalShippingOptions$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    orderUpdateCallbackConfig: "order_update_callback_config",
    additionalData: "additional_data",
  });
});

export function paypalOptionsToJSON(paypalOptions: PaypalOptions): string {
  return JSON.stringify(PaypalOptions$outboundSchema.parse(paypalOptions));
}
