/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type PaypalDirectOrderOptions = {
  /**
   * The ID of an existing PayPal order that was already created and approved by the buyer entirely outside of Gr4vy. Gr4vy retrieves this order and authorizes (or captures) it directly, without creating an order of its own.
   */
  orderId: string;
};

/** @internal */
export type PaypalDirectOrderOptions$Outbound = {
  order_id: string;
};

/** @internal */
export const PaypalDirectOrderOptions$outboundSchema: z.ZodType<
  PaypalDirectOrderOptions$Outbound,
  z.ZodTypeDef,
  PaypalDirectOrderOptions
> = z.object({
  orderId: z.string(),
}).transform((v) => {
  return remap$(v, {
    orderId: "order_id",
  });
});

export function paypalDirectOrderOptionsToJSON(
  paypalDirectOrderOptions: PaypalDirectOrderOptions,
): string {
  return JSON.stringify(
    PaypalDirectOrderOptions$outboundSchema.parse(paypalDirectOrderOptions),
  );
}
