/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PazeLocationAddress = {
  /**
   * Name of the organization or entity at the address.
   */
  name?: string | null | undefined;
  /**
   * Line 1 of the address.
   */
  line1: string;
  /**
   * Line 2 of the address.
   */
  line2?: string | null | undefined;
  /**
   * Line 3 of the address.
   */
  line3?: string | null | undefined;
  /**
   * City.
   */
  city: string;
  /**
   * State or region.
   */
  state: string;
  /**
   * Postal code.
   */
  zip: string;
  /**
   * ISO 3166-1 alpha-2 country code.
   */
  countryCode: string;
};

/** @internal */
export type PazeLocationAddress$Outbound = {
  name?: string | null | undefined;
  line1: string;
  line2?: string | null | undefined;
  line3?: string | null | undefined;
  city: string;
  state: string;
  zip: string;
  countryCode: string;
};

/** @internal */
export const PazeLocationAddress$outboundSchema: z.ZodType<
  PazeLocationAddress$Outbound,
  z.ZodTypeDef,
  PazeLocationAddress
> = z.object({
  name: z.nullable(z.string()).optional(),
  line1: z.string(),
  line2: z.nullable(z.string()).optional(),
  line3: z.nullable(z.string()).optional(),
  city: z.string(),
  state: z.string(),
  zip: z.string(),
  countryCode: z.string(),
});

export function pazeLocationAddressToJSON(
  pazeLocationAddress: PazeLocationAddress,
): string {
  return JSON.stringify(
    PazeLocationAddress$outboundSchema.parse(pazeLocationAddress),
  );
}
