/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PazeClient = {
  /**
   * Client identifier generated by Paze and shared during onboarding.
   */
  id: string;
  /**
   * Display name associated with the client for presentation purposes.
   */
  name?: string | null | undefined;
  /**
   * Client profile to use during checkout.
   */
  profileId?: string | null | undefined;
};

/** @internal */
export type PazeClient$Outbound = {
  id: string;
  name?: string | null | undefined;
  profileId?: string | null | undefined;
};

/** @internal */
export const PazeClient$outboundSchema: z.ZodType<
  PazeClient$Outbound,
  z.ZodTypeDef,
  PazeClient
> = z.object({
  id: z.string(),
  name: z.nullable(z.string()).optional(),
  profileId: z.nullable(z.string()).optional(),
});

export function pazeClientToJSON(pazeClient: PazeClient): string {
  return JSON.stringify(PazeClient$outboundSchema.parse(pazeClient));
}
