/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const PazeTransactionOptionsBillingPreference = {
  All: "ALL",
  None: "NONE",
} as const;
export type PazeTransactionOptionsBillingPreference = OpenEnum<
  typeof PazeTransactionOptionsBillingPreference
>;

export const PayloadTypeIndicator = {
  Id: "ID",
  Payment: "PAYMENT",
} as const;
export type PayloadTypeIndicator = OpenEnum<typeof PayloadTypeIndicator>;

export type PazeTransactionOptions = {
  /**
   * Merchant Category Code (MCC) of the merchant.
   */
  merchantCategoryCode?: string | null | undefined;
  /**
   * Verbosity of the billing address required by the merchant.
   */
  billingPreference?:
    | PazeTransactionOptionsBillingPreference
    | null
    | undefined;
  /**
   * ID returns `payloadId` only (default). PAYMENT returns `payloadId` and `securePayload`.
   */
  payloadTypeIndicator?: PayloadTypeIndicator | null | undefined;
};

/** @internal */
export const PazeTransactionOptionsBillingPreference$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  PazeTransactionOptionsBillingPreference
> = openEnums.outboundSchema(PazeTransactionOptionsBillingPreference);

/** @internal */
export const PayloadTypeIndicator$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  PayloadTypeIndicator
> = openEnums.outboundSchema(PayloadTypeIndicator);

/** @internal */
export type PazeTransactionOptions$Outbound = {
  merchantCategoryCode?: string | null | undefined;
  billingPreference?: string | null | undefined;
  payloadTypeIndicator?: string | null | undefined;
};

/** @internal */
export const PazeTransactionOptions$outboundSchema: z.ZodType<
  PazeTransactionOptions$Outbound,
  z.ZodTypeDef,
  PazeTransactionOptions
> = z.object({
  merchantCategoryCode: z.nullable(z.string()).optional(),
  billingPreference: z.nullable(
    PazeTransactionOptionsBillingPreference$outboundSchema,
  ).optional(),
  payloadTypeIndicator: z.nullable(PayloadTypeIndicator$outboundSchema)
    .optional(),
});

export function pazeTransactionOptionsToJSON(
  pazeTransactionOptions: PazeTransactionOptions,
): string {
  return JSON.stringify(
    PazeTransactionOptions$outboundSchema.parse(pazeTransactionOptions),
  );
}
