/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PazeSessionReviewRequest = {
  /**
   * Session reference identifier generated by the merchant. Must match the value sent in the Paze session create call.
   */
  sessionId: string;
  /**
   * Opaque token issued by the Paze service in the response from the most recent Paze UX interaction (checkout, change card, or change shipping address).
   */
  code: string;
  /**
   * The Paze OAuth access token returned by the Paze mobile session create call. Used to authenticate the request to Paze.
   */
  accessToken: string;
};

/** @internal */
export type PazeSessionReviewRequest$Outbound = {
  sessionId: string;
  code: string;
  accessToken: string;
};

/** @internal */
export const PazeSessionReviewRequest$outboundSchema: z.ZodType<
  PazeSessionReviewRequest$Outbound,
  z.ZodTypeDef,
  PazeSessionReviewRequest
> = z.object({
  sessionId: z.string(),
  code: z.string(),
  accessToken: z.string(),
});

export function pazeSessionReviewRequestToJSON(
  pazeSessionReviewRequest: PazeSessionReviewRequest,
): string {
  return JSON.stringify(
    PazeSessionReviewRequest$outboundSchema.parse(pazeSessionReviewRequest),
  );
}
