/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import { Refund, Refund$ } from "./refund";
import * as z from "zod";

/**
 * A list of refunds.
 */
export type Refunds = {
    /**
     * A list of refunds.
     */
    items?: Array<Refund> | undefined;
    /**
     * The limit applied to request. This represents the number of items that are at
     *
     * @remarks
     * maximum returned by this request.
     */
    limit?: number | undefined;
    /**
     * The cursor that represents the next page of results. Use the `cursor` query
     *
     * @remarks
     * parameter to fetch this page of items.
     */
    nextCursor?: string | null | undefined;
    /**
     * The cursor that represents the next page of results. Use the `cursor` query
     *
     * @remarks
     * parameter to fetch this page of items.
     */
    previousCursor?: string | null | undefined;
};

/** @internal */
export namespace Refunds$ {
    export const inboundSchema: z.ZodType<Refunds, z.ZodTypeDef, unknown> = z
        .object({
            items: z.array(Refund$.inboundSchema).optional(),
            limit: z.number().int().default(20),
            next_cursor: z.nullable(z.string()).optional(),
            previous_cursor: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                next_cursor: "nextCursor",
                previous_cursor: "previousCursor",
            });
        });

    export type Outbound = {
        items?: Array<Refund$.Outbound> | undefined;
        limit: number;
        next_cursor?: string | null | undefined;
        previous_cursor?: string | null | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Refunds> = z
        .object({
            items: z.array(Refund$.outboundSchema).optional(),
            limit: z.number().int().default(20),
            nextCursor: z.nullable(z.string()).optional(),
            previousCursor: z.nullable(z.string()).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                nextCursor: "next_cursor",
                previousCursor: "previous_cursor",
            });
        });
}
