/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const ReportSchedule = {
  Daily: "daily",
  Monthly: "monthly",
  Once: "once",
  Weekly: "weekly",
} as const;
export type ReportSchedule = OpenEnum<typeof ReportSchedule>;

/** @internal */
export const ReportSchedule$inboundSchema: z.ZodType<
  ReportSchedule,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(ReportSchedule);
/** @internal */
export const ReportSchedule$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  ReportSchedule
> = openEnums.outboundSchema(ReportSchedule);
