/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type RiskifiedAntiFraudOptionsShippingLine = {
  /**
   * The shipping address this delivery charge applies to. Must be `base-shipping-address` for the address derived from the transaction, or the `id` of an `additional_shipping_addresses` entry. Must not be provided when `additional_shipping_addresses` is empty.
   */
  shippingAddressId?: string | null | undefined;
};

/** @internal */
export type RiskifiedAntiFraudOptionsShippingLine$Outbound = {
  shipping_address_id?: string | null | undefined;
};

/** @internal */
export const RiskifiedAntiFraudOptionsShippingLine$outboundSchema: z.ZodType<
  RiskifiedAntiFraudOptionsShippingLine$Outbound,
  z.ZodTypeDef,
  RiskifiedAntiFraudOptionsShippingLine
> = z.object({
  shippingAddressId: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    shippingAddressId: "shipping_address_id",
  });
});

export function riskifiedAntiFraudOptionsShippingLineToJSON(
  riskifiedAntiFraudOptionsShippingLine: RiskifiedAntiFraudOptionsShippingLine,
): string {
  return JSON.stringify(
    RiskifiedAntiFraudOptionsShippingLine$outboundSchema.parse(
      riskifiedAntiFraudOptionsShippingLine,
    ),
  );
}
