/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const DeliveredTo = {
  ShippingAddress: "shipping_address",
  StorePickup: "store_pickup",
} as const;
export type DeliveredTo = OpenEnum<typeof DeliveredTo>;

export type RiskifiedAntiFraudOptionsLineItem = {
  /**
   * Indicates whether the item will be shipped or picked up.
   */
  deliveredTo?: DeliveredTo | null | undefined;
};

/** @internal */
export const DeliveredTo$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  DeliveredTo
> = openEnums.outboundSchema(DeliveredTo);

/** @internal */
export type RiskifiedAntiFraudOptionsLineItem$Outbound = {
  delivered_to?: string | null | undefined;
};

/** @internal */
export const RiskifiedAntiFraudOptionsLineItem$outboundSchema: z.ZodType<
  RiskifiedAntiFraudOptionsLineItem$Outbound,
  z.ZodTypeDef,
  RiskifiedAntiFraudOptionsLineItem
> = z.object({
  deliveredTo: z.nullable(DeliveredTo$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    deliveredTo: "delivered_to",
  });
});

export function riskifiedAntiFraudOptionsLineItemToJSON(
  riskifiedAntiFraudOptionsLineItem: RiskifiedAntiFraudOptionsLineItem,
): string {
  return JSON.stringify(
    RiskifiedAntiFraudOptionsLineItem$outboundSchema.parse(
      riskifiedAntiFraudOptionsLineItem,
    ),
  );
}
