/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  RiskifiedAntiFraudOptionsLineItem,
  RiskifiedAntiFraudOptionsLineItem$Outbound,
  RiskifiedAntiFraudOptionsLineItem$outboundSchema,
} from "./riskifiedantifraudoptionslineitem.js";

export type RiskifiedAntiFraudOptions = {
  /**
   * A list of line items details to override when passing to the Riskified API.
   */
  lineItems?: Array<RiskifiedAntiFraudOptionsLineItem> | null | undefined;
};

/** @internal */
export type RiskifiedAntiFraudOptions$Outbound = {
  line_items?:
    | Array<RiskifiedAntiFraudOptionsLineItem$Outbound>
    | null
    | undefined;
};

/** @internal */
export const RiskifiedAntiFraudOptions$outboundSchema: z.ZodType<
  RiskifiedAntiFraudOptions$Outbound,
  z.ZodTypeDef,
  RiskifiedAntiFraudOptions
> = z.object({
  lineItems: z.nullable(
    z.array(RiskifiedAntiFraudOptionsLineItem$outboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    lineItems: "line_items",
  });
});

export function riskifiedAntiFraudOptionsToJSON(
  riskifiedAntiFraudOptions: RiskifiedAntiFraudOptions,
): string {
  return JSON.stringify(
    RiskifiedAntiFraudOptions$outboundSchema.parse(riskifiedAntiFraudOptions),
  );
}
