/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The role to associate with the role assignment.
 */
export type RoleAssignmentRequestRole = {
    /**
     * The ID of the role to associate with the role assignment.
     */
    id: string;
};

/**
 * The type of the assignee to associate with the role assignment.
 */
export enum RoleAssignmentRequestType {
    User = "user",
}

/**
 * The assignee to associate with the role assignment.
 */
export type RoleAssignmentRequestAssignee = {
    /**
     * The type of the assignee to associate with the role assignment.
     */
    type: RoleAssignmentRequestType;
    /**
     * The ID of the assignee to associate with the role assignment.
     */
    id: string;
};

/**
 * A request to create a role assignment.
 */
export type RoleAssignmentRequest = {
    /**
     * The role to associate with the role assignment.
     */
    role: RoleAssignmentRequestRole;
    /**
     * The assignee to associate with the role assignment.
     */
    assignee: RoleAssignmentRequestAssignee;
};

/** @internal */
export namespace RoleAssignmentRequestRole$ {
    export const inboundSchema: z.ZodType<RoleAssignmentRequestRole, z.ZodTypeDef, unknown> =
        z.object({
            id: z.string(),
        });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RoleAssignmentRequestRole> =
        z.object({
            id: z.string(),
        });
}

/** @internal */
export namespace RoleAssignmentRequestType$ {
    export const inboundSchema = z.nativeEnum(RoleAssignmentRequestType);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace RoleAssignmentRequestAssignee$ {
    export const inboundSchema: z.ZodType<RoleAssignmentRequestAssignee, z.ZodTypeDef, unknown> =
        z.object({
            type: RoleAssignmentRequestType$.inboundSchema,
            id: z.string(),
        });

    export type Outbound = {
        type: string;
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RoleAssignmentRequestAssignee> =
        z.object({
            type: RoleAssignmentRequestType$.outboundSchema,
            id: z.string(),
        });
}

/** @internal */
export namespace RoleAssignmentRequest$ {
    export const inboundSchema: z.ZodType<RoleAssignmentRequest, z.ZodTypeDef, unknown> = z.object({
        role: z.lazy(() => RoleAssignmentRequestRole$.inboundSchema),
        assignee: z.lazy(() => RoleAssignmentRequestAssignee$.inboundSchema),
    });

    export type Outbound = {
        role: RoleAssignmentRequestRole$.Outbound;
        assignee: RoleAssignmentRequestAssignee$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RoleAssignmentRequest> =
        z.object({
            role: z.lazy(() => RoleAssignmentRequestRole$.outboundSchema),
            assignee: z.lazy(() => RoleAssignmentRequestAssignee$.outboundSchema),
        });
}
