/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  StripeConnectOptions,
  StripeConnectOptions$Outbound,
  StripeConnectOptions$outboundSchema,
} from "./stripeconnectoptions.js";

export type StripeOptions = {
  /**
   * Stripe options to support Stripe Connect
   */
  stripeConnect?: StripeConnectOptions | null | undefined;
};

/** @internal */
export type StripeOptions$Outbound = {
  stripe_connect?: StripeConnectOptions$Outbound | null | undefined;
};

/** @internal */
export const StripeOptions$outboundSchema: z.ZodType<
  StripeOptions$Outbound,
  z.ZodTypeDef,
  StripeOptions
> = z.object({
  stripeConnect: z.nullable(StripeConnectOptions$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    stripeConnect: "stripe_connect",
  });
});

export function stripeOptionsToJSON(stripeOptions: StripeOptions): string {
  return JSON.stringify(StripeOptions$outboundSchema.parse(stripeOptions));
}
