/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ShippingCarrier,
  ShippingCarrier$inboundSchema,
  ShippingCarrier$outboundSchema,
} from "./shippingcarrier.js";

export type Tracking = {
  /**
   * The tracking number for the shipment.
   */
  number: string;
  carrier: ShippingCarrier;
  /**
   * The URL to track the shipment.
   */
  url?: string | null | undefined;
};

/** @internal */
export const Tracking$inboundSchema: z.ZodType<
  Tracking,
  z.ZodTypeDef,
  unknown
> = z.object({
  number: z.string(),
  carrier: ShippingCarrier$inboundSchema,
  url: z.nullable(z.string()).optional(),
});
/** @internal */
export type Tracking$Outbound = {
  number: string;
  carrier: string;
  url?: string | null | undefined;
};

/** @internal */
export const Tracking$outboundSchema: z.ZodType<
  Tracking$Outbound,
  z.ZodTypeDef,
  Tracking
> = z.object({
  number: z.string(),
  carrier: ShippingCarrier$outboundSchema,
  url: z.nullable(z.string()).optional(),
});

export function trackingToJSON(tracking: Tracking): string {
  return JSON.stringify(Tracking$outboundSchema.parse(tracking));
}
export function trackingFromJSON(
  jsonString: string,
): SafeParseResult<Tracking, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tracking$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tracking' from JSON`,
  );
}
