/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  TransactionOutput,
  TransactionOutput$inboundSchema,
} from "./transactionoutput.js";
import { VoidStatus, VoidStatus$inboundSchema } from "./voidstatus.js";

export type TransactionVoidOutput = {
  /**
   * Always `transaction-void`.
   */
  type?: "transaction-void" | undefined;
  status: VoidStatus;
  /**
   * The standardized error code set by Gr4vy.
   */
  code: string | null;
  /**
   * This is the response code received from the payment service. This can be set to any value and is not standardized across different payment services.
   */
  rawResponseCode: string | null;
  /**
   * This is the response description received from the payment service. This can be set to any value and is not standardized across different payment services.
   */
  rawResponseDescription: string | null;
  /**
   * A full transaction resource.
   */
  transaction: TransactionOutput;
};

/** @internal */
export const TransactionVoidOutput$inboundSchema: z.ZodType<
  TransactionVoidOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("transaction-void").default("transaction-void"),
  status: VoidStatus$inboundSchema,
  code: z.nullable(z.string()),
  raw_response_code: z.nullable(z.string()),
  raw_response_description: z.nullable(z.string()),
  transaction: TransactionOutput$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "raw_response_code": "rawResponseCode",
    "raw_response_description": "rawResponseDescription",
  });
});

export function transactionVoidOutputFromJSON(
  jsonString: string,
): SafeParseResult<TransactionVoidOutput, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionVoidOutput$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionVoidOutput' from JSON`,
  );
}
