/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

export const TransactionIntent = {
  Authorize: "authorize",
  Capture: "capture",
} as const;
export type TransactionIntent = OpenEnum<typeof TransactionIntent>;

/** @internal */
export const TransactionIntent$inboundSchema: z.ZodType<
  TransactionIntent,
  z.ZodTypeDef,
  unknown
> = openEnums.inboundSchema(TransactionIntent);
/** @internal */
export const TransactionIntent$outboundSchema: z.ZodType<
  string,
  z.ZodTypeDef,
  TransactionIntent
> = openEnums.outboundSchema(TransactionIntent);
