/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type TransactionAuthorizationIncrementCreate = {
  /**
   * The amount by which to increment the authorization, in the smallest currency unit of the transaction's currency. For example, `1299` cents to increment the authorization by `$12.99`.
   */
  amount: number;
};

/** @internal */
export type TransactionAuthorizationIncrementCreate$Outbound = {
  amount: number;
};

/** @internal */
export const TransactionAuthorizationIncrementCreate$outboundSchema: z.ZodType<
  TransactionAuthorizationIncrementCreate$Outbound,
  z.ZodTypeDef,
  TransactionAuthorizationIncrementCreate
> = z.object({
  amount: z.number().int(),
});

export function transactionAuthorizationIncrementCreateToJSON(
  transactionAuthorizationIncrementCreate:
    TransactionAuthorizationIncrementCreate,
): string {
  return JSON.stringify(
    TransactionAuthorizationIncrementCreate$outboundSchema.parse(
      transactionAuthorizationIncrementCreate,
    ),
  );
}
