/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type TravelHubCustomData = {
  /**
   * The key of the custom data field.
   */
  name: string;
  /**
   * The value of the custom data field.
   */
  value: string;
  /**
   * The type of the custom data field.
   */
  type?: string | null | undefined;
};

/** @internal */
export type TravelHubCustomData$Outbound = {
  name: string;
  value: string;
  type?: string | null | undefined;
};

/** @internal */
export const TravelHubCustomData$outboundSchema: z.ZodType<
  TravelHubCustomData$Outbound,
  z.ZodTypeDef,
  TravelHubCustomData
> = z.object({
  name: z.string(),
  value: z.string(),
  type: z.nullable(z.string()).optional(),
});

export function travelHubCustomDataToJSON(
  travelHubCustomData: TravelHubCustomData,
): string {
  return JSON.stringify(
    TravelHubCustomData$outboundSchema.parse(travelHubCustomData),
  );
}
