/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  TravelHubCustomData,
  TravelHubCustomData$Outbound,
  TravelHubCustomData$outboundSchema,
} from "./travelhubcustomdata.js";

export type TravelhubOptions = {
  /**
   * A list of `customData` to pass to the TravelHub API.
   */
  customData?: Array<TravelHubCustomData> | null | undefined;
  /**
   * Customer company name to pass to the TravelHub API.
   */
  companyName?: string | null | undefined;
};

/** @internal */
export type TravelhubOptions$Outbound = {
  customData?: Array<TravelHubCustomData$Outbound> | null | undefined;
  companyName?: string | null | undefined;
};

/** @internal */
export const TravelhubOptions$outboundSchema: z.ZodType<
  TravelhubOptions$Outbound,
  z.ZodTypeDef,
  TravelhubOptions
> = z.object({
  customData: z.nullable(z.array(TravelHubCustomData$outboundSchema))
    .optional(),
  companyName: z.nullable(z.string()).optional(),
});

export function travelhubOptionsToJSON(
  travelhubOptions: TravelhubOptions,
): string {
  return JSON.stringify(
    TravelhubOptions$outboundSchema.parse(travelhubOptions),
  );
}
