/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { Field, Field$Outbound, Field$outboundSchema } from "./field.js";

export type VerifyCredentials = {
  /**
   * The ID of the payment service definition to verify the fields against
   */
  paymentServiceDefinitionId: string;
  /**
   * The optional ID of the configured payment service. New fields will be merged with any existing fields already stored before they are verified.
   */
  paymentServiceId?: string | null | undefined;
  /**
   * The fields and their values, or a set of updated fields to merge with existing values.
   */
  fields: Array<Field>;
};

/** @internal */
export type VerifyCredentials$Outbound = {
  payment_service_definition_id: string;
  payment_service_id?: string | null | undefined;
  fields: Array<Field$Outbound>;
};

/** @internal */
export const VerifyCredentials$outboundSchema: z.ZodType<
  VerifyCredentials$Outbound,
  z.ZodTypeDef,
  VerifyCredentials
> = z.object({
  paymentServiceDefinitionId: z.string(),
  paymentServiceId: z.nullable(z.string()).optional(),
  fields: z.array(Field$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    paymentServiceDefinitionId: "payment_service_definition_id",
    paymentServiceId: "payment_service_id",
  });
});

export function verifyCredentialsToJSON(
  verifyCredentials: VerifyCredentials,
): string {
  return JSON.stringify(
    VerifyCredentials$outboundSchema.parse(verifyCredentials),
  );
}
