name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    
    timeout-minutes: 3
    strategy:
      matrix:
        node:
          - 22.x

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
         npm i

      - name: Run tests
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          npx vitest

      - uses: hmarr/auto-approve-action@v4
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        with:
          github-token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}

  merge:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: automerge
        name: automerge
        if: "github.event.pull_request.user.login == 'github-actions[bot]'"
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          MERGE_LABELS: ''
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_ERROR_FAIL: true
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: false
          UPDATE_METHOD: rebase