name: CI (PRs)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    timeout-minutes: 3
    strategy:
      matrix:
        node:
          - 22.x

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
         npm i

      - name: Run tests
        # env:
          # PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # GR4VY_ID: ${{ secrets.GR4VY_ID }}
        run: |
          npx vitest
      
      - name: Mark for automerge
        if: "github.actor == 'github-actions[bot]'"
        uses: actions/labeler@v5

      - id: automerge
        name: automerge
        if: "github.actor == 'github-actions[bot]'"
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: ${{ secrets.DISPATCH_ACCESS_TOKEN }}