name: Generate SDK
permissions:
    checks: write
    contents: write
    pull-requests: write
    statuses: write
"on":
    repository_dispatch:
        types: openapi_published
    workflow_dispatch:
        inputs:
            force:
                description: Force generation of SDKs
                type: boolean
                default: false
            set_version:
                description: optionally set a specific SDK version
                type: string
            target:
                description: 'optionally: set a specific target to generate, default is all'
                type: string
    schedule:
        - cron: 0 0 * * *
jobs:
    generate:
        uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
        with:
            force: ${{ github.event.inputs.force }}
            mode: pr
            set_version: ${{ github.event.inputs.set_version }}
            speakeasy_version: latest
            target: ${{ github.event.inputs.target }}
        secrets:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
            npm_token: ${{ secrets.NPM_TOKEN }}
            speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

    notify:
        needs: generate
        runs-on: ubuntu-latest
        if: always()
        steps:
          - name: Slack Notification
            uses: rtCamp/action-slack-notify@v2
            if: github.ref == 'refs/heads/master'
            env:
                SLACK_USERNAME: Typescript SDK 
                SLACK_TITLE: Typescript SDK
                SLACK_WEBHOOK: ${{ secrets.SLACK_SDK_WEBHOOK_URL }}
                SLACK_CHANNEL: sdk-updates
                SLACK_MSG_AUTHOR: gr4vy-code
                SLACK_ICON_EMOJI: ":gr4vy:"
                SLACK_COLOR: "${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}"
                SLACK_MESSAGE_ON_SUCCESS: "SDK generation succeeded - ${{ github.event.head_commit.message }}"
                SLACK_MESSAGE_ON_FAILURE: "SDK generation failed - ${{ github.event.head_commit.message }}"