name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  repository_dispatch:
    types: openapi_published
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * *
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: ${{ github.event.inputs.force }}
      mode: pr 
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

  dispatch:
    needs: generate
    strategy:
      matrix:
        repo:
          - gr4vy/gr4vy-docs-mintlify
    runs-on: ubuntu-latest
    steps:
      - name: Notify SDKs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: sdk_updated