name: Publish
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  push:
    branches:
      - main
    paths:
      - .speakeasy/gen.lock
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      target: typescript
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

  dispatch:
    needs: publish
    strategy:
      matrix:
        repo:
          - gr4vy/gr4vy-docs-mintlify
    runs-on: ubuntu-latest
    steps:
      - name: Notify SDKs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: sdk_updated